/* eslint-disable react/no-unescaped-entities -- Localized editorial JSX intentionally uses readable punctuation. */
import type { Guide } from "@/lib/guides";
import type { LocalizedLocale } from "@/lib/i18n";
import type { PolicyPage } from "@/lib/policy-pages";

export const localizedAboutPages: Record<LocalizedLocale, PolicyPage> = {
  "zh-cn": {
    eyebrow: "关于 PULLVIO",
    title: "打造一种更清晰、更安心的媒体工作方式。",
    description: "Pullvio 是一款浏览器在线媒体工具，围绕清晰选择、可靠处理和负责任使用而设计。",
      body: <><h2>为什么要做 Pullvio</h2><p>许多在线媒体工具充斥着含糊的格式名称、干扰性广告、虚假按钮和无法验证的隐私承诺。Pullvio 希望提供一个更克制的选择：用清晰的界面说明格式、画质、文件大小与媒体处理过程。</p><p>Pullvio 可在手机和电脑浏览器中直接使用，支持将您有权保存的在线媒体处理为 MP4 视频或 MP3 音频。访客无需账号即可体验，免费账号则可在合理使用范围内继续使用并管理下载记录。</p><h2>我们关注什么</h2><p>产品围绕可靠的端到端流程设计：从链接解析、格式选择到文件交付，让每一步都清晰可控。新增来源、格式和账户能力会在稳定验证后逐步提供。</p><h2>产品原则</h2><ul><li>用清楚的语言解释格式和可用画质。</li><li>尊重真实源画质，不承诺人为制造的高分辨率。</li><li>在主要工作流中提示授权与负责任使用。</li><li>明确说明临时文件的处理与删除方式。</li><li>让免费用户在手机和电脑上都能轻松使用。</li></ul><h2 id="editorial-standards">编辑规范</h2><p>Pullvio 指南由 Pullvio 编辑团队撰写与审核。技术文章会区分文档事实与推断，尽可能引用原始规范，并明确说明尚未验证的功能。只有内容发生实质变化时才更新审核日期，不会仅为了看起来更新而修改日期。</p><div className="content-callout"><strong>独立产品</strong><p>Pullvio 与 TikTok、Vimeo、SoundCloud 或其他媒体平台没有隶属或合作关系。平台名称仅用于说明兼容性。</p></div></>,
  },
  es: {
    eyebrow: "SOBRE PULLVIO",
    title: "Una forma más clara y tranquila de trabajar con contenido multimedia.",
    description: "Pullvio es una herramienta multimedia para el navegador, creada alrededor de decisiones claras, procesamiento fiable y uso responsable.",
      body: <><h2>Por qué existe Pullvio</h2><p>Muchas herramientas multimedia online están rodeadas de formatos confusos, publicidad intrusiva, botones falsos y afirmaciones de privacidad difíciles de comprobar. Pullvio ofrece una alternativa más cuidada que explica formatos, calidad, tamaño y procesamiento con claridad.</p><p>Pullvio funciona directamente en navegadores móviles y de escritorio. Permite guardar contenido autorizado como video MP4 o audio MP3. Los visitantes pueden probarlo sin cuenta y una cuenta gratuita permite continuar dentro de límites de uso razonable y conservar el historial.</p><h2>En qué nos centramos</h2><p>El producto está diseñado como un flujo completo y fiable: análisis del enlace, selección de formato y entrega del archivo. Añadimos nuevas fuentes, formatos y funciones de cuenta después de comprobar su estabilidad.</p><h2>Nuestros principios</h2><ul><li>Explicar formatos y calidad disponible con lenguaje claro.</li><li>Respetar la calidad de origen sin prometer resoluciones artificiales.</li><li>Hacer visibles los permisos y el uso responsable.</li><li>Explicar el tratamiento y la eliminación de archivos temporales.</li><li>Mantener una experiencia gratuita clara en móvil y ordenador.</li></ul><h2 id="editorial-standards">Normas editoriales</h2><p>Las guías son escritas y revisadas por el equipo editorial de Pullvio. Los artículos técnicos separan documentación e inferencias, enlazan fuentes primarias cuando es posible y no presentan funciones sin verificar como hechos. La fecha de revisión solo cambia cuando el contenido cambia de forma sustancial.</p><div className="content-callout"><strong>Producto independiente</strong><p>Pullvio no está afiliado con TikTok, Vimeo, SoundCloud ni otras plataformas. Los nombres se utilizan únicamente para describir compatibilidad.</p></div></>,
  },
};

export const localizedPolicyPages: Record<LocalizedLocale, Record<"contact" | "privacy" | "terms" | "copyright" | "acceptable-use", PolicyPage>> = {
  "zh-cn": {
    contact: {
      eyebrow: "联系 PULLVIO", title: "联系 Pullvio 团队。", description: "如有产品、隐私、无障碍或版权问题，请通过对应邮箱联系我们。",
      body: <><h2>产品与一般反馈</h2><p>产品建议、无障碍问题、合作咨询或指南纠错，请发送至 <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>。</p><h2>隐私问题</h2><p>个人数据、Cookie、账户信息或隐私请求，请发送至 <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>。</p><h2>版权通知</h2><p>版权与下架事项，请发送至 <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a>，并提供作品、相关位置、您的代理权限和可靠联系方式。</p><h2>回复时间</h2><p>我们通常会在五个工作日内确认有效的支持和政策邮件，但这些邮箱不提供紧急或实时支持。</p></>,
    },
    privacy: {
      eyebrow: "隐私", title: "隐私政策。", description: "本政策说明 Pullvio 为提供账户、媒体处理、安全防护和支持服务而使用的数据。",
      body: <><h2>Pullvio 如何处理数据</h2><p>我们仅使用完成链接解析、格式选择、文件交付、账户管理和安全防护所合理需要的信息。</p><h2>可能处理的数据</h2><ul><li><strong>访问数据：</strong>IP 地址、浏览器类型、请求页面、时间和诊断信息。</li><li><strong>处理数据：</strong>提交的来源链接、格式和画质选择、任务状态及有限技术日志。</li><li><strong>账户数据：</strong>邮箱、账户标识、会话令牌和登录方式。</li><li><strong>您发送的信息：</strong>联系邮件及您主动提供的内容。</li></ul><h2>Cookie 与本地存储</h2><p>安全 Cookie 用于维持登录会话；主题和语言偏好可保存在浏览器本地。</p><h2>临时文件与保留</h2><p>媒体处理文件仅在完成和交付任务所需期间临时保留，之后自动删除。安全和支持记录可能因防止滥用、争议处理或法律义务保留更长时间。</p><h2>您的请求</h2><p>如需访问、更正或删除个人数据，请发送邮件至 <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>。请求可能受适用法律和必要安全记录限制。</p></>,
    },
    terms: {
      eyebrow: "服务条款", title: "使用条款。", description: "本条款适用于 Pullvio 的媒体处理工具、免费账号与发布的指南。",
      body: <><h2>服务范围</h2><p>Pullvio 提供在线媒体处理、免费账号功能与教育内容。支持的来源、格式和合理使用限制可能随产品更新。</p><h2>允许的使用</h2><p>请仅处理您拥有的内容、公共领域作品、按许可条件使用的开放内容，或您获得许可或拥有其他合法保存权利的媒体。</p><h2>禁止行为</h2><ul><li>绕过 DRM、付费墙、登录、私密账户或其他访问控制。</li><li>侵犯版权、隐私、公开权、合同或其他权利。</li><li>恶意自动化、超量请求、未经允许的安全测试或干扰服务。</li><li>冒充 Pullvio 与第三方平台存在隶属关系。</li></ul><h2>账号与合理使用</h2><p>您有责任保护账号安全。免费账号不设固定下载次数，但恶意自动化、过度占用资源、规避安全限制或影响服务可用性的活动可能受到限制。</p><h2>联系我们</h2><p>条款问题请发送至 <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>。</p></>,
    },
    copyright: {
      eyebrow: "版权", title: "版权与下架政策。", description: "Pullvio 面向获得授权的媒体工作流，并为权利人提供问题报告渠道。",
      body: <><h2>尊重创作成果</h2><p>Pullvio 适用于用户自己的作品、公共领域材料、开放许可作品，以及用户获得明确许可或拥有其他合法依据的内容。</p><h2>提交版权通知</h2><p>请将通知发送至 <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a>，并包含：</p><ol><li>受保护作品或授权代理人的身份信息。</li><li>用于定位相关活动的 Pullvio URL、任务编号或其他准确信息。</li><li>您的姓名、组织和可靠联系方式。</li><li>您认为相关使用未经授权的原因。</li><li>信息准确且您有权代理的声明。</li><li>适用情况下的实体或电子签名。</li></ol><h2>审查与回应</h2><p>我们可能要求补充信息、限制访问、保留必要记录或采取其他适当措施。重复侵权或滥用可能导致任务取消、账户限制或终止。</p></>,
    },
    "acceptable-use": {
      eyebrow: "可接受使用", title: "可接受使用政策。", description: "Pullvio 用于合法的个人、创作、存档和教育工作流，而非规避访问控制。",
      body: <><h2>可接受的示例</h2><ul><li>备份您自己创作并上传的媒体。</li><li>按照许可条件保存公共领域或开放许可作品。</li><li>处理创作者或权利人明确授权的媒体。</li><li>为剪辑、教学、研究、无障碍或离线使用准备获得授权的资料。</li></ul><h2>不可接受的使用</h2><ul><li>未经许可或其他合法依据下载或传播受版权保护的内容。</li><li>绕过 DRM、付费墙、身份验证、私密账户、地区限制或其他访问控制。</li><li>处理非法、剥削性、虐待性或侵犯隐私的内容。</li><li>利用自动化压垮服务、逃避额度或未经授权转售服务。</li><li>传播恶意软件、探测基础设施或干扰其他用户。</li></ul><h2>执行措施</h2><p>Pullvio 可能限制请求、暂停任务、限制账户、保留安全记录，或配合有效法律程序。用户应自行确认媒体权利并遵守适用法律和平台规则。</p></>,
    },
  },
  es: {
    contact: {
      eyebrow: "CONTACTO", title: "Habla con el equipo de Pullvio.", description: "Dirige tus preguntas sobre producto, privacidad, accesibilidad o derechos de autor al canal adecuado.",
      body: <><h2>Producto y comentarios generales</h2><p>Escribe a <a href="mailto:hello@pullvio.com">hello@pullvio.com</a> para sugerencias, accesibilidad, colaboraciones o correcciones de nuestras guías.</p><h2>Privacidad</h2><p>Escribe a <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a> para consultas sobre datos personales, cookies, cuentas o solicitudes de privacidad.</p><h2>Derechos de autor</h2><p>Envía avisos a <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a> e incluye la obra, la ubicación relevante, tu autoridad para actuar y un medio de contacto fiable.</p><h2>Tiempo de respuesta</h2><p>Intentamos confirmar los mensajes legítimos en cinco días laborables. Estos canales no ofrecen soporte urgente ni en tiempo real.</p></>,
    },
    privacy: {
      eyebrow: "PRIVACIDAD", title: "Política de privacidad.", description: "Esta política explica los datos que Pullvio utiliza para cuentas, procesamiento multimedia, seguridad y soporte.",
      body: <><h2>Cómo tratamos los datos</h2><p>Usamos únicamente la información razonablemente necesaria para analizar enlaces, preparar archivos, entregar resultados, gestionar cuentas y proteger el servicio.</p><h2>Datos que podemos tratar</h2><ul><li><strong>Acceso:</strong> dirección IP, navegador, URL solicitada, fecha y diagnóstico.</li><li><strong>Procesamiento:</strong> URL de origen, formato y calidad solicitados, estado del trabajo y registros técnicos limitados.</li><li><strong>Cuenta:</strong> correo, identificador, tokens de sesión y método de acceso.</li><li><strong>Mensajes:</strong> la dirección y el contenido que decidas enviarnos.</li></ul><h2>Cookies y almacenamiento local</h2><p>Las cookies de seguridad mantienen la sesión. El tema y el idioma pueden guardarse localmente en el navegador.</p><h2>Archivos temporales</h2><p>Los archivos de procesamiento se conservan solo durante el tiempo necesario para completar y entregar el trabajo y después se eliminan automáticamente. Algunos registros de seguridad o soporte pueden conservarse para prevenir abusos, resolver disputas o cumplir obligaciones legítimas.</p><h2>Tus solicitudes</h2><p>Solicita acceso, corrección o eliminación en <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>, sujeto a la ley aplicable y a registros de seguridad necesarios.</p></>,
    },
    terms: {
      eyebrow: "TÉRMINOS", title: "Términos de uso.", description: "Estos términos regulan las herramientas multimedia, cuentas gratuitas y guías de Pullvio.",
      body: <><h2>Disponibilidad del servicio</h2><p>Pullvio ofrece procesamiento multimedia online, cuentas gratuitas y contenido educativo. Las fuentes, formatos y límites de uso razonable pueden cambiar.</p><h2>Uso permitido</h2><p>Usa Pullvio solo con contenido propio, de dominio público, con licencia abierta usada según sus condiciones o que tengas permiso o derecho legal para guardar.</p><h2>Conductas prohibidas</h2><ul><li>Eludir DRM, muros de pago, accesos, cuentas privadas u otras restricciones.</li><li>Infringir derechos de autor, privacidad, imagen, contrato u otros derechos.</li><li>Abusar mediante automatización, solicitudes excesivas, pruebas de seguridad sin permiso o interferencias.</li><li>Presentar Pullvio como afiliado a una plataforma externa.</li></ul><h2>Cuentas y uso razonable</h2><p>Eres responsable de proteger tu cuenta. Las cuentas gratuitas no tienen un límite fijo, pero la automatización abusiva, el consumo excesivo de recursos, la evasión de controles y la actividad que ponga en riesgo el servicio pueden restringirse.</p><h2>Contacto</h2><p>Envía preguntas a <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>.</p></>,
    },
    copyright: {
      eyebrow: "DERECHOS DE AUTOR", title: "Política de derechos de autor y retirada.", description: "Pullvio está pensado para usos autorizados y ofrece un canal para comunicar problemas concretos.",
      body: <><h2>Respeto por el trabajo creativo</h2><p>Pullvio se utiliza para obras propias, material de dominio público, contenido con licencia abierta y obras que el usuario tiene permiso o base legal para guardar.</p><h2>Enviar un aviso</h2><p>Escribe a <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a> e incluye:</p><ol><li>La obra protegida o el representante autorizado.</li><li>La URL de Pullvio, referencia del trabajo u otra información exacta.</li><li>Tu nombre, organización y contacto.</li><li>El motivo por el que consideras que el uso no está autorizado.</li><li>Una declaración de exactitud y autoridad para actuar.</li><li>La firma física o electrónica cuando corresponda.</li></ol><h2>Revisión y respuesta</h2><p>Podemos pedir aclaraciones, restringir acceso, conservar registros necesarios o tomar medidas proporcionadas. La reincidencia puede causar cancelación de trabajos o restricción de cuentas.</p></>,
    },
    "acceptable-use": {
      eyebrow: "USO ACEPTABLE", title: "Política de uso aceptable.", description: "Pullvio sirve para flujos personales, creativos, educativos y de archivo legítimos, no para eludir controles.",
      body: <><h2>Ejemplos aceptables</h2><ul><li>Crear copias de seguridad de contenido propio.</li><li>Guardar obras de dominio público o con licencia abierta según sus condiciones.</li><li>Trabajar con contenido autorizado por el creador o titular.</li><li>Preparar referencias autorizadas para edición, enseñanza, investigación, accesibilidad o uso offline.</li></ul><h2>Usos no aceptados</h2><ul><li>Descargar o distribuir obras protegidas sin permiso o base legal.</li><li>Eludir DRM, pagos, autenticación, cuentas privadas, restricciones geográficas u otros controles.</li><li>Procesar contenido ilegal, abusivo, explotador o invasivo de la privacidad.</li><li>Usar automatización para saturar el servicio, evitar límites o revender acceso sin permiso.</li><li>Introducir malware, sondear la infraestructura o interferir con otros usuarios.</li></ul><h2>Aplicación</h2><p>Pullvio puede limitar solicitudes, suspender trabajos, restringir cuentas, conservar registros de seguridad o colaborar con procesos legales válidos. Cada usuario es responsable de comprobar sus derechos y cumplir las normas aplicables.</p></>,
    },
  },
};

export const localizedGuideHubs: Record<LocalizedLocale, { eyebrow: string; title: string; description: string; guideLabel: string }> = {
  "zh-cn": { eyebrow: "PULLVIO 实用指南", title: "更明智地选择媒体格式。", description: "用清晰、实用的说明了解格式、分辨率、存储空间、源画质与负责任使用。", guideLabel: "指南" },
  es: { eyebrow: "GUÍAS DE PULLVIO", title: "Toma mejores decisiones multimedia.", description: "Explicaciones claras sobre formatos, resolución, almacenamiento, calidad de origen y uso responsable.", guideLabel: "GUÍA" },
};

const allLocalizedGuides: Record<LocalizedLocale, Guide[]> = {
  "zh-cn": [
    {
      slug: "mp4-vs-mp3", eyebrow: "格式指南", title: "MP4 和 MP3 有什么区别？应该选哪个？", readingTime: "阅读约 6 分钟",
      description: "从用途、兼容性、画质、编辑需求和存储空间比较 MP4 视频与 MP3 音频，选择适合自己的格式。",
      body: <><p>需要画面和声音时选择 MP4；只需要收听内容时选择 MP3。这个简单原则适用于大多数情况，但兼容性、文件大小和后续编辑也会影响最终选择。</p><h2>MP4 适合保留完整视频</h2><p>MP4 是一种多媒体容器，可以同时包含视频、音频、字幕和章节信息。手机、电脑、浏览器、电视、演示软件和常见剪辑工具通常都能打开标准 MP4 文件。</p><p>当画面本身有价值，例如自己的视频备份、获得授权的课程演示或需要离线观看的视觉内容时，MP4 是更实用的选择。</p><h2>MP3 适合只保留声音</h2><p>MP3 是音频格式，不包含原视频画面。去掉视频流后，文件通常更小，也更适合放入音乐播放器、播客应用、语言学习或笔记工作流。</p><p>把视频转换成 MP3 不会提升原始音质。低质量的源文件仍然受到源音频限制，因此没有必要盲目选择最高码率。</p><h2>画质、音质与文件大小</h2><p>文件大小取决于时长、码率、编码器、帧率、分辨率和内容复杂度。MP3 通常比 MP4 小很多；对于语音内容，中等码率往往已经足够，而音乐和复杂声音可能需要更高码率。</p><h2>如果还要编辑，尽量保留源文件</h2><p>反复转换会造成质量损失。如果计划剪辑、调色或长期归档，应保存最接近合法来源的高质量版本。MP3 适合收听，但通常不适合作为长期编辑母版。</p><div className="content-callout"><strong>快速选择</strong><p>需要画面就选 MP4；只需要声音和更小文件就选 MP3；需要长期编辑则保留您有权使用的最高质量源文件。</p></div><h2>格式不会改变版权归属</h2><p>选择 MP4 或 MP3 不会改变作品的权利状态。请只保存自己创作的内容、公共领域或符合开放许可条件的作品，以及您获得明确许可或拥有其他合法保存权利的媒体。</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "视频画质指南", title: "480p、720p、1080p、2K 与 4K 怎么选？", readingTime: "阅读约 7 分钟",
      description: "理解常见视频分辨率、真实源画质、屏幕尺寸、带宽和文件大小，选择适合的清晰度。",
      body: <><p>对于大多数现代屏幕，1080p 是兼顾清晰度和文件大小的默认选择。存储空间或网络有限时可选 720p；只有来源确实提供更多细节，并且设备或编辑流程能够利用时，2K 或 4K 才有明显价值。</p><h2>分辨率只是画质的一部分</h2><p>分辨率表示每一帧包含多少像素，但不能说明码率、编码效率、帧率、色彩和录制质量。编码良好的 1080p 可能比严重压缩的 4K 看起来更清晰。</p><p>把 720p 放大到 4K 只会增加像素数量，无法恢复原本不存在的细节。可信的工具应该展示来源真正提供的画质上限。</p><h2>常见分辨率适合什么场景</h2><ul><li><strong>480p：</strong>文件较小，适合慢速网络和画面不重要的内容。</li><li><strong>720p：</strong>适合手机、小屏幕和希望节省空间的用户。</li><li><strong>1080p：</strong>适合笔记本、显示器、演示和大多数电视，是通用首选。</li><li><strong>1440p / 2K：</strong>适合较大的高密度显示器、屏幕录制和需要裁切的编辑。</li><li><strong>2160p / 4K：</strong>适合大屏幕、近距离查看、授权归档和专业编辑，但文件与处理成本更高。</li></ul><h2>帧率和码率同样重要</h2><p>运动画面需要足够的帧率与码率。同为 1080p，60 帧运动视频通常比 24 帧访谈需要更多数据。压缩过度会产生马赛克、色带和运动模糊，无论分辨率标签多高都无法弥补。</p><div className="content-callout"><strong>推荐默认值</strong><p>来源存在 1080p 时先选 1080p；想减小文件或网络较慢时选 720p；只有真实来源和明确用途同时存在时才选择 2K 或 4K。</p></div><h2>不要制造虚假的画质承诺</h2><p>Pullvio 计划只展示合法来源实际提供的清晰度。媒体处理流程完成真实验证前，我们不会承诺任何平台一定支持某种分辨率。</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "负责任使用指南", title: "如何合法、负责任地保存在线媒体？", readingTime: "阅读约 8 分钟",
      description: "使用实用检查清单判断自己的作品、公共领域、开放许可、创作者授权和平台规则。",
      body: <><p>最安全的起点是：保存自己创作的媒体、明确进入公共领域的作品、按照许可条件使用的开放内容，或权利人明确允许您保存的内容。能够访问某个链接，并不自动代表拥有复制或再次使用的许可。</p><div className="content-callout"><strong>重要说明</strong><p>本指南只提供一般教育信息，不构成法律意见。版权例外、合同规则和平台条款会因国家与具体情况而不同。</p></div><h2>1. 先确认所有权</h2><p>如果作品由您录制、制作并上传，保留备份通常是最明确的场景。但仍要确认其中没有使用他人控制的音乐、画面、艺术品或表演。</p><h2>2. 阅读明确的许可</h2><p>开放许可会提前授予某些权利，但通常附带署名、禁止商业使用、禁止演绎或相同方式共享等条件。建议记录作者、来源 URL、许可名称和访问日期。</p><h2>3. 谨慎判断公共领域</h2><p>作品是否属于公共领域可能因国家不同。旧作品的新录音、修复、翻译、编曲或扫描也可能包含新的受保护元素。优先使用会清楚说明权利状态的可靠资料库。</p><h2>4. 向创作者或权利人取得许可</h2><p>没有明确许可时，应取得与实际用途一致的书面授权，包括作品、允许的行为、是否可商用、授权期限和署名要求。保存相关消息或协议。</p><h2>5. 区分保存与再次发布</h2><p>允许个人离线保存，不一定意味着可以重新上传、传播、编辑、出售或加入其他产品。每一种后续行为都需要单独判断。</p><h2>6. 尊重平台规则和访问控制</h2><p>不要绕过 DRM、付费墙、私密账户、登录验证、地域限制或其他技术保护。Pullvio 不会以规避这些限制为产品目标。</p><h2>保存前检查清单</h2><ol><li>能否识别创作者或权利人？</li><li>是否由您完整创作？</li><li>是否存在明确的公共领域声明或开放许可？</li><li>是否理解并满足许可的全部条件？</li><li>是否获得与用途相匹配的书面授权？</li><li>是否避开私密内容与访问控制？</li><li>是否记录来源、作者、许可和日期？</li></ol><p>不能确定时，不要把不确定当作许可。优先使用创作者提供的官方下载、请求确认、选择权利清楚的替代内容，或在后果重要时咨询专业人士。</p></>,
    },
    {
      slug: "save-youtube-videos", eyebrow: "平台指南", title: "如何合法、负责任地下载保存 YouTube 视频？", readingTime: "阅读约 8 分钟",
      description: "介绍如何合法下载自己上传的 YouTube 视频、带有 CC 协议的共享视频，以及使用官方离线功能。",
      body: <><p>YouTube 拥有海量的视频资源。为了学习、参考或二次创作，用户常常需要将视频保存到本地离线使用。然而，能够通过浏览器在线播放，并不意味着拥有下载或复制的合法权利。理解平台条款与著作权边界，是安全工作流的核心。</p><h2>1. 使用官方离线下载功能</h2><p>对于大多数观众，最安全、最合规的保存方式是使用官方离线模式。订阅 YouTube Premium 会员后，您可以在官方手机 App 及部分受支持的电脑浏览器中直接下载视频。这些文件仅保存在 App 内部，不会绕过平台的广告变现或访问控制。</p><h2>2. 下载您自己上传的视频</h2><p>如果您是创作者，您对自己制作并上传的原始视频拥有完全的控制权。您可以通过 YouTube Studio（创作者后台）直接下载自己往期视频的 720p 或 1080p 备份。如果需要批量备份整个频道的视频，可以使用 Google Takeout（谷歌归档）进行一次性打包下载。</p><h2>3. 寻找 Creative Commons（CC 共享协议）内容</h2><p>有些创作者会以 Creative Commons（CC-BY 署名协议）发布视频。这代表他们预先授权公众在注明来源的前提下，下载、传播或对该视频进行二次创作。您可以在 YouTube 搜索时，使用“过滤条件”筛选出仅包含 CC 共享协议的视频。</p><h2>4. 取得创作者的明确授权</h2><p>如果您希望在教学、演示或个人剪辑中引用其他创作者的画面，最负责任的做法是通过其频道“关于”页面中的商务邮箱直接联系对方。获得明确的书面授权（即使是简单的邮件确认）能帮您规避潜在的版权纠纷。</p><h2>5. 尊重版权与访问限制</h2><p>不要使用浏览器工具绕过数字版权管理（DRM）、下载私人视频，或未经授权保存受版权保护的商业媒体（如电影、电视剧或官方音乐视频）。Pullvio 不支持绕过任何加密保护或私密限制。</p><div className="content-callout"><strong>合规判定清单</strong><p>该视频是您自己上传的吗？它是否使用了 CC 共享协议？您是否获得了创作者的邮件授权？如果是，那么进行本地保存通常是合规且负责任的。</p></div></>,
    },
    {
      slug: "save-tiktok-videos", eyebrow: "平台指南", title: "如何保存 TikTok 视频为 MP4 或提取 MP3 音频？", readingTime: "阅读约 7 分钟",
      description: "了解 TikTok 内置的保存选项、提取 MP3 音频的合理场景，以及在保存和引用视频时如何尊重创作者。",
      body: <><p>TikTok 是短视频和流行音频的重要策源地。虽然平台鼓励分享，但将视频保存为本地 MP4 或提取为 MP3 音频时，需要关注内置功能限制与创作者版权设置。尊重原作者的创作权，是负责任使用短媒体的前提。</p><h2>1. 优先使用 TikTok 内置的“保存视频”功能</h2><p>在默认情况下，TikTok 提供了官方下载渠道。如果创作者开启了权限，您可以点击视频上的“分享”图标并选择“保存视频”，直接下载至手机相册。生成的 MP4 会包含视频画面、音频以及原作者的用户名水印。这是最受推荐且符合平台规范的保存方式。</p><h2>2. 合理提取视频中的 MP3 音频</h2><p>如果您想将视频中的背景音乐、配音或原声保存为 MP3，以便于离线学习或创作参考，可以通过格式转换提取音频。但提取音频不会赋予您该声音的版权，请仅在个人参考或获得授权的情况下使用，切勿随意传播他人原创的声音片段。</p><h2>3. 尊重创作者的下载权限设置</h2><p>创作者可以随时在后台关闭其视频的“允许下载”选项。如果某段视频无法直接保存，说明作者希望将其内容保留在 TikTok 平台内。请尊重创作者的意愿，不要强行绕过该限制去获取媒体文件。</p><h2>4. 关注版权音乐的合规使用</h2><p>TikTok 视频中经常包含受版权保护的商业音乐。尽管平台获得了在应用内播放这些音乐的许可，但如果您将视频保存到本地并重新发布到其他平台，仍可能会面临版权投诉。请确保对保存文件中的所有声音流拥有合理的使用权。</p><h2>5. 做好创作者署名</h2><p>如果您获得许可对保存的 TikTok 视频进行引用（例如做反应视频、分析或教学），请务必在显著位置标明原作者的账户名称，并附上原始链接。尊重他人劳动成果是使用媒体的基本原则。</p><div className="content-callout"><strong>快速检查清单</strong><p>原视频是否允许官方下载？您提取的音频是否仅用于个人学习？后续分享是否会完整署名？遵守这些规范，能让您的媒体工作流更安心。</p></div></>,
    },
  ],
  es: [
    {
      slug: "mp4-vs-mp3", eyebrow: "GUÍA DE FORMATOS", title: "MP4 o MP3: ¿qué formato deberías elegir?", readingTime: "6 min de lectura",
      description: "Compara MP4 y MP3 por uso, compatibilidad, calidad, edición y espacio para elegir el formato adecuado.",
      body: <><p>Elige MP4 cuando necesites imagen y sonido. Elige MP3 cuando solo quieras escuchar. Esta regla resuelve la mayoría de los casos, aunque la compatibilidad, el tamaño y la edición posterior también importan.</p><h2>MP4 conserva el video completo</h2><p>MP4 es un contenedor multimedia capaz de guardar video, audio, subtítulos y otros datos. Los teléfonos, ordenadores, navegadores, televisores y editores habituales suelen admitir combinaciones MP4 comunes.</p><p>Es la opción práctica para copias autorizadas donde la imagen tiene valor: videos propios, demostraciones permitidas, presentaciones o contenido visual para ver sin conexión.</p><h2>MP3 conserva únicamente el audio</h2><p>MP3 no incluye la imagen original. Al eliminar el video, el archivo suele ser mucho más pequeño y cómodo para reproductores, podcasts, clases de idiomas, entrevistas o notas de voz.</p><p>Convertir un archivo a MP3 no mejora el sonido original. Una fuente de baja calidad seguirá limitada por esa fuente, por lo que el bitrate máximo no siempre aporta una mejora audible.</p><h2>Calidad, tamaño y edición</h2><p>El tamaño depende de la duración, bitrate, códec, resolución y complejidad. Para voz, un bitrate moderado suele ser suficiente; la música puede justificar más información. Si vas a editar, conserva la fuente autorizada de mayor calidad y evita conversiones repetidas.</p><div className="content-callout"><strong>Elección rápida</strong><p>¿Necesitas la imagen? MP4. ¿Solo necesitas escuchar y ahorrar espacio? MP3. ¿Vas a editar o archivar? Conserva la mejor fuente que tengas derecho a utilizar.</p></div><h2>El formato no cambia los derechos</h2><p>Usa ambos formatos únicamente con obras propias, contenido de dominio público o licencia abierta dentro de sus condiciones, o material para el que tengas permiso u otro derecho legal.</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "GUÍA DE CALIDAD", title: "¿480p, 720p, 1080p, 2K o 4K?", readingTime: "7 min de lectura",
      description: "Comprende resolución, calidad de origen, tamaño de pantalla, ancho de banda y espacio antes de elegir.",
      body: <><p>1080p es una buena opción general para muchas pantallas modernas. Elige 720p cuando el espacio o la conexión sean limitados, y reserva 2K o 4K para fuentes que realmente contengan ese detalle y usos que puedan aprovecharlo.</p><h2>La resolución no es toda la calidad</h2><p>La resolución indica el número de píxeles, pero no describe el bitrate, la eficiencia del códec, los fotogramas por segundo, el color ni la grabación original. Un 1080p bien codificado puede verse mejor que un 4K excesivamente comprimido.</p><p>Ampliar una fuente 720p a un marco 4K crea más píxeles, pero no recupera detalle. Una herramienta fiable debe mostrar el límite real de la fuente.</p><h2>Qué resolución encaja con cada uso</h2><ul><li><strong>480p:</strong> archivos pequeños y conexiones lentas.</li><li><strong>720p:</strong> móviles, pantallas pequeñas y ahorro de espacio.</li><li><strong>1080p:</strong> portátiles, monitores, presentaciones y muchos televisores.</li><li><strong>1440p / 2K:</strong> monitores grandes y edición con recortes.</li><li><strong>2160p / 4K:</strong> pantallas grandes, archivo autorizado y edición exigente, con mayor coste de almacenamiento.</li></ul><h2>También importan los fotogramas y el bitrate</h2><p>El movimiento rápido necesita suficientes datos. Un video deportivo a 60 fps puede requerir más bitrate que una entrevista a 24 fps con la misma resolución. La compresión excesiva crea bloques y movimiento borroso.</p><div className="content-callout"><strong>Recomendación</strong><p>Empieza con 1080p cuando exista. Baja a 720p para archivos pequeños o conexiones limitadas. Sube a 2K o 4K solo cuando la fuente sea genuina y tengas un motivo claro.</p></div><h2>Sin promesas artificiales</h2><p>El flujo previsto de Pullvio mostrará únicamente las calidades disponibles en una fuente permitida. No prometeremos resoluciones para una plataforma hasta probar el proceso completo.</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "GUÍA DE USO RESPONSABLE", title: "Cómo guardar contenido online de forma responsable", readingTime: "8 min de lectura",
      description: "Revisa propiedad, dominio público, licencias abiertas, permiso del creador y reglas de la plataforma antes de guardar contenido.",
      body: <><p>El punto de partida más seguro es guardar contenido creado por ti, obras claramente de dominio público, material con licencia abierta usado dentro de sus condiciones o contenido cuyo titular te haya dado permiso. Poder acceder a una URL no concede automáticamente permiso para copiarla o reutilizarla.</p><div className="content-callout"><strong>Importante</strong><p>Esta guía ofrece información educativa general, no asesoramiento jurídico. Las excepciones de copyright, los contratos y las condiciones de las plataformas varían según el país y la situación.</p></div><h2>1. Empieza por la propiedad</h2><p>Conservar una copia de una obra que grabaste, produjiste y publicaste suele ser el caso más claro. Aun así, comprueba si contiene música, imágenes, arte o actuaciones controladas por otras personas.</p><h2>2. Lee la licencia completa</h2><p>Una licencia abierta puede exigir atribución, limitar el uso comercial, prohibir modificaciones o exigir compartir con la misma licencia. Guarda el autor, la URL, el nombre de la licencia y la fecha de acceso.</p><h2>3. Verifica el dominio público</h2><p>El estado de dominio público puede cambiar entre jurisdicciones. Una grabación, traducción, restauración o digitalización reciente de una obra antigua puede incluir elementos protegidos.</p><h2>4. Solicita permiso adecuado</h2><p>Cuando no exista una licencia clara, pide autorización por escrito que identifique la obra, los usos permitidos, la duración, el uso comercial y la atribución. Conserva el mensaje o acuerdo.</p><h2>5. Guardar no significa republicar</h2><p>El permiso para una copia personal no incluye necesariamente subir, distribuir, editar, vender o integrar la obra en otro producto. Evalúa cada acción por separado.</p><h2>6. Respeta las reglas y controles</h2><p>No eludas DRM, muros de pago, cuentas privadas, autenticación, restricciones geográficas ni otras protecciones técnicas. Pullvio no está pensado para ofrecer esos atajos.</p><h2>Lista de comprobación</h2><ol><li>¿Puedes identificar al creador o titular?</li><li>¿Creaste toda la obra?</li><li>¿Existe una declaración clara de dominio público o licencia?</li><li>¿Cumples todas sus condiciones?</li><li>¿Tienes permiso escrito para el uso previsto?</li><li>¿Evitas contenido privado y controles de acceso?</li><li>¿Has registrado fuente, autor, licencia y fecha?</li></ol><p>Si no estás seguro, no trates la duda como permiso. Usa la descarga oficial del creador, pide una aclaración, busca una alternativa con derechos claros o consulta a un profesional cuando las consecuencias sean importantes.</p></>,
    },
    {
      slug: "save-youtube-videos", eyebrow: "GUÍA DE PLATAFORMAS", title: "Cómo guardar videos de YouTube de forma responsable", readingTime: "8 min de lectura",
      description: "Aprende a guardar legalmente tus propias subidas de YouTube, usar descargas oficiales y descargar clips con licencia Creative Commons.",
      body: <><p>YouTube alberga miles de millones de videos. Guardar contenido en tu dispositivo para estudiar, hacer referencias o reutilizarlo de forma creativa es una necesidad común, pero el acceso técnico no otorga automáticamente el derecho legal de copiarlo. Conozca las opciones de descarga y las licencias es clave para un flujo de trabajo responsable.</p><h2>1. Utiliza las descargas oficiales sin conexión</h2><p>La forma más sencilla y segura de guardar videos para verlos sin conexión es el modo nativo de la plataforma. La suscripción a YouTube Premium te permite descargar videos directamente en la aplicación móvil oficial y en navegadores de escritorio compatibles. Estos archivos se guardan dentro de la aplicación sin eludir los controles del creador.</p><h2>2. Descarga tus propios videos subidos</h2><p>Si eres creador de contenido, tienes pleno derecho legal a guardar copias de seguridad de los videos que creaste y subiste originalmente. Puedes descargar tus propios videos en 720p o 1080p desde YouTube Studio. Para copias de seguridad completas de tu canal, Google Takeout ofrece una herramienta de exportación por lotes.</p><h2>3. Busca licencias Creative Commons (CC-BY)</h2><p>Algunos creadores publican sus videos bajo la licencia Creative Commons Attribution (CC-BY). Esta licencia otorga permiso al público para descargar, compartir y reutilizar el video, siempre que se atribuya al autor original. Puedes buscar videos con esta licencia utilizando los filtros de búsqueda de YouTube.</p><h2>4. Solicita permiso directo al creador</h2><p>Si necesitas usar un clip de otro creador para un proyecto colaborativo o académico, lo más responsable es contactar con el titular de los derechos. Muchos canales incluyen un correo electrónico de contacto en su pestaña "Información". Un acuerdo escrito protege a ambas partes.</p><h2>5. Respeta el copyright y el DRM</h2><p>No utilices herramientas externas para eludir la gestión de derechos digitales (DRM), descargar videos privados o guardar contenido comercial protegido (como películas o videos musicales oficiales) sin autorización. Pullvio no elude medidas tecnológicas de protección.</p><div className="content-callout"><strong>Comprobación rápida</strong><p>¿El video es de tu canal? ¿Tiene licencia Creative Commons? ¿Cuentas con la autorización escrita del creador? Si es así, guardarlo sin conexión suele ser una práctica responsable.</p></div></>,
    },
    {
      slug: "save-tiktok-videos", eyebrow: "GUÍA DE PLATAFORMAS", title: "Cómo guardar videos de TikTok en MP4 y extraer audio MP3", readingTime: "7 min de lectura",
      description: "Entiende la descarga nativa de TikTok, cómo extraer audio MP3 de forma responsable y las buenas prácticas sobre marcas de agua y derechos.",
      body: <><p>TikTok se basa en videos cortos y tendencias de audio. Aunque la aplicación facilita la compartición, guardar clips en tu dispositivo como archivos MP4 o extraer audio como MP3 requiere comprender las funciones nativas y los derechos de los creadores. Un uso respetuoso protege a los autores originales.</p><h2>1. Utiliza la opción nativa \"Guardar video\"</h2><p>Por defecto, TikTok incluye una función de descarga. Si el creador lo permite, puedes guardar el video en tu carrete pulsando el icono \"Compartir\" y seleccionando \"Guardar video\". El archivo incluirá la marca de agua con el nombre del creador. Este método oficial respeta la elección del autor de permitir descargas.</p><h2>2. Extrae audio a MP3 para referencias</h2><p>Cuando necesites guardar una pista de voz o sonido de un video para estudiar o usar de referencia, puedes extraer el audio en MP3. Recuerda que convertir a MP3 no otorga la propiedad. Usa el archivo únicamente para fines personales o proyectos autorizados, no publiques voces ajenas sin permiso.</p><h2>3. Respeta los ajustes del creador</h2><p>Los creadores pueden desactivar la opción de descarga de sus videos. Si la descarga directa está deshabilitada, es una indicación clara de que el creador prefiere mantener su contenido dentro de la aplicación. Respeta esta preferencia y evita eludir sus ajustes.</p><h2>4. Ten en cuenta la música comercial</h2><p>Muchos de los videos de TikTok utilizan música comercial. Aunque la plataforma cuenta con licencias para reproducir estos temas dentro de la app, descargar el video y subirlo a otro lugar puede infringir los derechos de autor. Asegúrate de tener los derechos de cualquier audio guardado.</p><h2>5. Atribuye la autoría</h2><p>Si tienes permiso para reutilizar un video (por ejemplo, para una crítica o proyecto académico), menciona siempre al creador original indicando su nombre de usuario y enlazando al video de origen. La atribución es una regla fundamental del uso responsable de medios.</p><div className="content-callout"><strong>Lista de comprobación</strong><p>¿El video permite la descarga oficial? ¿Usas el audio solo como referencia personal? ¿Mencionarás al creador si compartes el clip? Seguir estas pautas garantiza un uso responsable.</p></div></>,
    },
  ],
};

export const localizedGuides: Record<LocalizedLocale, Guide[]> = {
  "zh-cn": allLocalizedGuides["zh-cn"].filter(({ slug }) => slug !== "save-youtube-videos"),
  es: allLocalizedGuides.es.filter(({ slug }) => slug !== "save-youtube-videos"),
};

export function getLocalizedGuide(locale: LocalizedLocale, slug: string) {
  return localizedGuides[locale].find((guide) => guide.slug === slug);
}
