import type { Guide } from "@/lib/guides";
import type { LocalizedLocale } from "@/lib/i18n";
import type { PolicyPage } from "@/lib/policy-pages";

export const localizedAboutPages: Record<LocalizedLocale, PolicyPage> = {
  "zh-cn": {
    eyebrow: "关于 PULLVIO",
    title: "打造一种更清晰、更安心的媒体工作方式。",
    description: "Pullvio 是一款浏览器在线媒体工具，围绕清晰选择、可靠处理和负责任使用而设计。",
    body: <><h2>为什么要做 Pullvio</h2><p>许多在线媒体工具充斥着含糊的格式名称、干扰性广告、虚假按钮和无法验证的隐私承诺。Pullvio 希望提供一个更克制的选择：用清晰的界面说明格式、画质、文件大小与媒体处理过程。</p><p>Pullvio 可在手机和电脑浏览器中直接使用，支持将您有权保存的在线媒体处理为 MP4 视频或 MP3 音频，并通过 Free 与 Pro 方案满足不同使用频率。</p><h2>我们关注什么</h2><p>产品围绕可靠的端到端流程设计：从链接解析、格式选择到文件交付，让每一步都清晰可控。新增来源、格式和账户能力会在稳定验证后逐步提供。</p><h2>产品原则</h2><ul><li>用清楚的语言解释格式和可用画质。</li><li>尊重真实源画质，不承诺人为制造的高分辨率。</li><li>在主要工作流中提示授权与负责任使用。</li><li>明确说明临时文件的处理与删除方式。</li><li>让免费用户在手机和电脑上都能轻松使用。</li></ul><div className="content-callout"><strong>独立产品</strong><p>Pullvio 与 YouTube、TikTok、Vimeo、X、SoundCloud 或其他媒体平台没有隶属或合作关系。平台名称仅用于说明兼容性。</p></div></>,
  },
  es: {
    eyebrow: "SOBRE PULLVIO",
    title: "Una forma más clara y tranquila de trabajar con contenido multimedia.",
    description: "Pullvio es una herramienta multimedia para el navegador, creada alrededor de decisiones claras, procesamiento fiable y uso responsable.",
    body: <><h2>Por qué existe Pullvio</h2><p>Muchas herramientas multimedia online están rodeadas de formatos confusos, publicidad intrusiva, botones falsos y afirmaciones de privacidad difíciles de comprobar. Pullvio ofrece una alternativa más cuidada que explica formatos, calidad, tamaño y procesamiento con claridad.</p><p>Pullvio funciona directamente en navegadores móviles y de escritorio. Permite guardar contenido autorizado como video MP4 o audio MP3, con planes Free y Pro para distintas necesidades.</p><h2>En qué nos centramos</h2><p>El producto está diseñado como un flujo completo y fiable: análisis del enlace, selección de formato y entrega del archivo. Añadimos nuevas fuentes, formatos y funciones de cuenta después de comprobar su estabilidad.</p><h2>Nuestros principios</h2><ul><li>Explicar formatos y calidad disponible con lenguaje claro.</li><li>Respetar la calidad de origen sin prometer resoluciones artificiales.</li><li>Hacer visibles los permisos y el uso responsable.</li><li>Explicar el tratamiento y la eliminación de archivos temporales.</li><li>Mantener una experiencia gratuita clara en móvil y ordenador.</li></ul><div className="content-callout"><strong>Producto independiente</strong><p>Pullvio no está afiliado con YouTube, TikTok, Vimeo, X, SoundCloud ni otras plataformas. Los nombres se utilizan únicamente para describir compatibilidad.</p></div></>,
  },
};

export const localizedPolicyPages: Record<LocalizedLocale, Record<"contact" | "privacy" | "terms" | "copyright" | "acceptable-use", PolicyPage>> = {
  "zh-cn": {
    contact: {
      eyebrow: "联系 PULLVIO", title: "联系 Pullvio 团队。", description: "如有产品、隐私、无障碍或版权问题，请通过对应邮箱联系我们。",
      body: <><h2>产品与一般反馈</h2><p>产品建议、无障碍问题、合作咨询或指南纠错，请发送至 <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>。</p><h2>隐私问题</h2><p>个人数据、Cookie、账户信息或隐私请求，请发送至 <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>。</p><h2>版权通知</h2><p>版权与下架事项，请发送至 <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a>，并提供作品、相关位置、您的代理权限和可靠联系方式。</p><h2>回复时间</h2><p>我们通常会在五个工作日内确认有效的支持和政策邮件，但这些邮箱不提供紧急或实时支持。</p></>,
    },
    privacy: {
      eyebrow: "隐私", title: "隐私政策。", description: "本政策说明 Pullvio 为提供账户、媒体处理、安全防护和支持服务而使用的数据。",
      body: <><h2>Pullvio 如何处理数据</h2><p>我们仅使用完成链接解析、格式选择、文件交付、账户管理和安全防护所合理需要的信息。</p><h2>可能处理的数据</h2><ul><li><strong>访问数据：</strong>IP 地址、浏览器类型、请求页面、时间和诊断信息。</li><li><strong>处理数据：</strong>提交的来源链接、格式和画质选择、任务状态及有限技术日志。</li><li><strong>账户数据：</strong>邮箱、账户标识、会话令牌和登录方式。</li><li><strong>账单数据：</strong>支付由支付服务商处理；Pullvio 接收订阅状态、账单和有限交易记录。</li><li><strong>您发送的信息：</strong>联系邮件及您主动提供的内容。</li></ul><h2>Cookie 与本地存储</h2><p>安全 Cookie 用于维持登录会话；主题和语言偏好可保存在浏览器本地。</p><h2>临时文件与保留</h2><p>媒体处理文件仅在完成和交付任务所需期间临时保留，之后自动删除。安全、账单和支持记录可能因反欺诈、会计、争议处理或法律义务保留更长时间。</p><h2>您的请求</h2><p>如需访问、更正或删除个人数据，请发送邮件至 <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>。请求可能受适用法律和必要安全记录限制。</p></>,
    },
    terms: {
      eyebrow: "服务条款", title: "使用条款。", description: "本条款适用于 Pullvio 的媒体处理工具、账户、指南以及 Free 和 Pro 方案。",
      body: <><h2>服务范围</h2><p>Pullvio 提供在线媒体处理、账户功能、教育内容以及 Free 和 Pro 方案。支持的来源、格式、额度和价格可能随产品更新。</p><h2>允许的使用</h2><p>请仅处理您拥有的内容、公共领域作品、按许可条件使用的开放内容，或您获得许可或拥有其他合法保存权利的媒体。</p><h2>禁止行为</h2><ul><li>绕过 DRM、付费墙、登录、私密账户或其他访问控制。</li><li>侵犯版权、隐私、公开权、合同或其他权利。</li><li>恶意自动化、超量请求、未经允许的安全测试或干扰服务。</li><li>冒充 Pullvio 与第三方平台存在隶属关系。</li></ul><h2>账户与订阅</h2><p>您有责任保护账户安全。价格、周期、额度、续订、取消和退款信息会在购买前展示。</p><h2>联系我们</h2><p>条款问题请发送至 <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>。</p></>,
    },
    copyright: {
      eyebrow: "版权", title: "版权与下架政策。", description: "Pullvio 面向获得授权的媒体工作流，并为权利人提供问题报告渠道。",
      body: <><h2>尊重创作成果</h2><p>Pullvio 适用于用户自己的作品、公共领域材料、开放许可作品，以及用户获得明确许可或拥有其他合法依据的内容。</p><h2>提交版权通知</h2><p>请将通知发送至 <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a>，并包含：</p><ol><li>受保护作品或授权代理人的身份信息。</li><li>用于定位相关活动的 Pullvio URL、任务编号或其他准确信息。</li><li>您的姓名、组织和可靠联系方式。</li><li>您认为相关使用未经授权的原因。</li><li>信息准确且您有权代理的声明。</li><li>适用情况下的实体或电子签名。</li></ol><h2>审查与回应</h2><p>我们可能要求补充信息、限制访问、保留必要记录或采取其他适当措施。重复侵权或滥用可能导致任务取消、账户限制或终止。</p></>,
    },
    "acceptable-use": {
      eyebrow: "可接受使用", title: "可接受使用政策。", description: "Pullvio 用于合法的个人、创作、存档和教育工作流，而非规避访问控制。",
      body: <><h2>可接受的示例</h2><ul><li>备份您自己创作并上传的媒体。</li><li>按照许可条件保存公共领域或开放许可作品。</li><li>处理创作者或权利人明确授权的媒体。</li><li>为剪辑、教学、研究、无障碍或离线使用准备获得授权的资料。</li></ul><h2>不可接受的使用</h2><ul><li>未经许可或其他合法依据下载或传播受版权保护的内容。</li><li>绕过 DRM、付费墙、身份验证、私密账户、地区限制或其他访问控制。</li><li>处理非法、剥削性、虐待性或侵犯隐私的内容。</li><li>利用自动化压垮服务、逃避额度或未经授权转售服务。</li><li>传播恶意软件、探测基础设施或干扰其他用户。</li></ul><h2>执行措施</h2><p>Pullvio 可能限制请求、暂停任务、限制账户、保留安全记录，或配合有效法律程序。用户应自行确认媒体权利并遵守适用法律和平台规则。</p></>,
    },
  },
  es: {
    contact: {
      eyebrow: "CONTACTO", title: "Habla con el equipo de Pullvio.", description: "Dirige tus preguntas sobre producto, privacidad, accesibilidad o derechos de autor al canal adecuado.",
      body: <><h2>Producto y comentarios generales</h2><p>Escribe a <a href="mailto:hello@pullvio.com">hello@pullvio.com</a> para sugerencias, accesibilidad, colaboraciones o correcciones de nuestras guías.</p><h2>Privacidad</h2><p>Escribe a <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a> para consultas sobre datos personales, cookies, cuentas o solicitudes de privacidad.</p><h2>Derechos de autor</h2><p>Envía avisos a <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a> e incluye la obra, la ubicación relevante, tu autoridad para actuar y un medio de contacto fiable.</p><h2>Tiempo de respuesta</h2><p>Intentamos confirmar los mensajes legítimos en cinco días laborables. Estos canales no ofrecen soporte urgente ni en tiempo real.</p></>,
    },
    privacy: {
      eyebrow: "PRIVACIDAD", title: "Política de privacidad.", description: "Esta política explica los datos que Pullvio utiliza para cuentas, procesamiento multimedia, seguridad y soporte.",
      body: <><h2>Cómo tratamos los datos</h2><p>Usamos únicamente la información razonablemente necesaria para analizar enlaces, preparar archivos, entregar resultados, gestionar cuentas y proteger el servicio.</p><h2>Datos que podemos tratar</h2><ul><li><strong>Acceso:</strong> dirección IP, navegador, URL solicitada, fecha y diagnóstico.</li><li><strong>Procesamiento:</strong> URL de origen, formato y calidad solicitados, estado del trabajo y registros técnicos limitados.</li><li><strong>Cuenta:</strong> correo, identificador, tokens de sesión y método de acceso.</li><li><strong>Facturación:</strong> el proveedor procesa el pago; Pullvio recibe el estado de la suscripción, facturas y registros limitados.</li><li><strong>Mensajes:</strong> la dirección y el contenido que decidas enviarnos.</li></ul><h2>Cookies y almacenamiento local</h2><p>Las cookies de seguridad mantienen la sesión. El tema y el idioma pueden guardarse localmente en el navegador.</p><h2>Archivos temporales</h2><p>Los archivos de procesamiento se conservan solo durante el tiempo necesario para completar y entregar el trabajo y después se eliminan automáticamente. Algunos registros de seguridad, facturación o soporte pueden conservarse por obligaciones legítimas.</p><h2>Tus solicitudes</h2><p>Solicita acceso, corrección o eliminación en <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>, sujeto a la ley aplicable y a registros de seguridad necesarios.</p></>,
    },
    terms: {
      eyebrow: "TÉRMINOS", title: "Términos de uso.", description: "Estos términos regulan las herramientas multimedia, cuentas, guías y planes Free y Pro de Pullvio.",
      body: <><h2>Disponibilidad del servicio</h2><p>Pullvio ofrece procesamiento multimedia online, cuentas, contenido educativo y planes Free y Pro. Las fuentes, formatos, límites y precios pueden cambiar.</p><h2>Uso permitido</h2><p>Usa Pullvio solo con contenido propio, de dominio público, con licencia abierta usada según sus condiciones o que tengas permiso o derecho legal para guardar.</p><h2>Conductas prohibidas</h2><ul><li>Eludir DRM, muros de pago, accesos, cuentas privadas u otras restricciones.</li><li>Infringir derechos de autor, privacidad, imagen, contrato u otros derechos.</li><li>Abusar mediante automatización, solicitudes excesivas, pruebas de seguridad sin permiso o interferencias.</li><li>Presentar Pullvio como afiliado a una plataforma externa.</li></ul><h2>Cuentas y suscripciones</h2><p>Eres responsable de proteger tu cuenta. El precio, periodo, límites, renovación, cancelación y reembolso aplicables se muestran antes de comprar.</p><h2>Contacto</h2><p>Envía preguntas a <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>.</p></>,
    },
    copyright: {
      eyebrow: "DERECHOS DE AUTOR", title: "Política de derechos de autor y retirada.", description: "Pullvio está pensado para usos autorizados y ofrece un canal para comunicar problemas concretos.",
      body: <><h2>Respeto por el trabajo creativo</h2><p>Pullvio se utiliza para obras propias, material de dominio público, contenido con licencia abierta y obras que el usuario tiene permiso o base legal para guardar.</p><h2>Enviar un aviso</h2><p>Escribe a <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a> e incluye:</p><ol><li>La obra protegida o el representante autorizado.</li><li>La URL de Pullvio, referencia del trabajo u otra información exacta.</li><li>Tu nombre, organización y contacto.</li><li>El motivo por el que consideras que el uso no está autorizado.</li><li>Una declaración de exactitud y autoridad para actuar.</li><li>La firma física o electrónica cuando corresponda.</li></ol><h2>Revisión y respuesta</h2><p>Podemos pedir aclaraciones, restringir acceso, conservar registros necesarios o tomar medidas proporcionadas. La reincidencia puede causar cancelación de trabajos o restricción de cuentas.</p></>,
    },
    "acceptable-use": {
      eyebrow: "USO ACEPTABLE", title: "Política de uso aceptable.", description: "Pullvio sirve para flujos personales, creativos, educativos y de archivo legítimos, no para eludir controles.",
      body: <><h2>Ejemplos aceptables</h2><ul><li>Crear copias de seguridad de contenido propio.</li><li>Guardar obras de dominio público o con licencia abierta según sus condiciones.</li><li>Trabajar con contenido autorizado por el creador o titular.</li><li>Preparar referencias autorizadas para edición, enseñanza, investigación, accesibilidad o uso offline.</li></ul><h2>Usos no aceptados</h2><ul><li>Descargar o distribuir obras protegidas sin permiso o base legal.</li><li>Eludir DRM, pagos, autenticación, cuentas privadas, restricciones geográficas u otros controles.</li><li>Procesar contenido ilegal, abusivo, explotador o invasivo de la privacidad.</li><li>Usar automatización para saturar el servicio, evitar límites o revender acceso sin permiso.</li><li>Introducir malware, sondear la infraestructura o interferir con otros usuarios.</li></ul><h2>Aplicación</h2><p>Pullvio puede limitar solicitudes, suspender trabajos, restringir cuentas, conservar registros de seguridad o colaborar con procesos legales válidos. Cada usuario es responsable de comprobar sus derechos y cumplir las normas aplicables.</p></>,
    },
  },
};

export const localizedGuideHubs: Record<LocalizedLocale, { eyebrow: string; title: string; description: string; guideLabel: string }> = {
  "zh-cn": { eyebrow: "PULLVIO 实用指南", title: "更明智地选择媒体格式。", description: "用清晰、实用的说明了解格式、分辨率、存储空间、源画质与负责任使用。", guideLabel: "指南" },
  es: { eyebrow: "GUÍAS DE PULLVIO", title: "Toma mejores decisiones multimedia.", description: "Explicaciones claras sobre formatos, resolución, almacenamiento, calidad de origen y uso responsable.", guideLabel: "GUÍA" },
};

export const localizedGuides: Record<LocalizedLocale, Guide[]> = {
  "zh-cn": [
    {
      slug: "mp4-vs-mp3", eyebrow: "格式指南", title: "MP4 和 MP3 有什么区别？应该选哪个？", readingTime: "阅读约 6 分钟",
      description: "从用途、兼容性、画质、编辑需求和存储空间比较 MP4 视频与 MP3 音频，选择适合自己的格式。",
      body: <><p>需要画面和声音时选择 MP4；只需要收听内容时选择 MP3。这个简单原则适用于大多数情况，但兼容性、文件大小和后续编辑也会影响最终选择。</p><h2>MP4 适合保留完整视频</h2><p>MP4 是一种多媒体容器，可以同时包含视频、音频、字幕和章节信息。手机、电脑、浏览器、电视、演示软件和常见剪辑工具通常都能打开标准 MP4 文件。</p><p>当画面本身有价值，例如自己的视频备份、获得授权的课程演示或需要离线观看的视觉内容时，MP4 是更实用的选择。</p><h2>MP3 适合只保留声音</h2><p>MP3 是音频格式，不包含原视频画面。去掉视频流后，文件通常更小，也更适合放入音乐播放器、播客应用、语言学习或笔记工作流。</p><p>把视频转换成 MP3 不会提升原始音质。低质量的源文件仍然受到源音频限制，因此没有必要盲目选择最高码率。</p><h2>画质、音质与文件大小</h2><p>文件大小取决于时长、码率、编码器、帧率、分辨率和内容复杂度。MP3 通常比 MP4 小很多；对于语音内容，中等码率往往已经足够，而音乐和复杂声音可能需要更高码率。</p><h2>如果还要编辑，尽量保留源文件</h2><p>反复转换会造成质量损失。如果计划剪辑、调色或长期归档，应保存最接近合法来源的高质量版本。MP3 适合收听，但通常不适合作为长期编辑母版。</p><div className="content-callout"><strong>快速选择</strong><p>需要画面就选 MP4；只需要声音和更小文件就选 MP3；需要长期编辑则保留您有权使用的最高质量源文件。</p></div><h2>格式不会改变版权归属</h2><p>选择 MP4 或 MP3 不会改变作品的权利状态。请只保存自己创作的内容、公共领域或符合开放许可条件的作品，以及您获得明确许可或拥有其他合法保存权利的媒体。</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "视频画质指南", title: "480p、720p、1080p、2K 与 4K 怎么选？", readingTime: "阅读约 7 分钟",
      description: "理解常见视频分辨率、真实源画质、屏幕尺寸、带宽和文件大小，选择适合的清晰度。",
      body: <><p>对于大多数现代屏幕，1080p 是兼顾清晰度和文件大小的默认选择。存储空间或网络有限时可选 720p；只有来源确实提供更多细节，并且设备或编辑流程能够利用时，2K 或 4K 才有明显价值。</p><h2>分辨率只是画质的一部分</h2><p>分辨率表示每一帧包含多少像素，但不能说明码率、编码效率、帧率、色彩和录制质量。编码良好的 1080p 可能比严重压缩的 4K 看起来更清晰。</p><p>把 720p 放大到 4K 只会增加像素数量，无法恢复原本不存在的细节。可信的工具应该展示来源真正提供的画质上限。</p><h2>常见分辨率适合什么场景</h2><ul><li><strong>480p：</strong>文件较小，适合慢速网络和画面不重要的内容。</li><li><strong>720p：</strong>适合手机、小屏幕和希望节省空间的用户。</li><li><strong>1080p：</strong>适合笔记本、显示器、演示和大多数电视，是通用首选。</li><li><strong>1440p / 2K：</strong>适合较大的高密度显示器、屏幕录制和需要裁切的编辑。</li><li><strong>2160p / 4K：</strong>适合大屏幕、近距离查看、授权归档和专业编辑，但文件与处理成本更高。</li></ul><h2>帧率和码率同样重要</h2><p>运动画面需要足够的帧率与码率。同为 1080p，60 帧运动视频通常比 24 帧访谈需要更多数据。压缩过度会产生马赛克、色带和运动模糊，无论分辨率标签多高都无法弥补。</p><div className="content-callout"><strong>推荐默认值</strong><p>来源存在 1080p 时先选 1080p；想减小文件或网络较慢时选 720p；只有真实来源和明确用途同时存在时才选择 2K 或 4K。</p></div><h2>不要制造虚假的画质承诺</h2><p>Pullvio 计划只展示合法来源实际提供的清晰度。媒体处理流程完成真实验证前，我们不会承诺任何平台一定支持某种分辨率。</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "负责任使用指南", title: "如何合法、负责任地保存在线媒体？", readingTime: "阅读约 8 分钟",
      description: "使用实用检查清单判断自己的作品、公共领域、开放许可、创作者授权和平台规则。",
      body: <><p>最安全的起点是：保存自己创作的媒体、明确进入公共领域的作品、按照许可条件使用的开放内容，或权利人明确允许您保存的内容。能够访问某个链接，并不自动代表拥有复制或再次使用的许可。</p><div className="content-callout"><strong>重要说明</strong><p>本指南只提供一般教育信息，不构成法律意见。版权例外、合同规则和平台条款会因国家与具体情况而不同。</p></div><h2>1. 先确认所有权</h2><p>如果作品由您录制、制作并上传，保留备份通常是最明确的场景。但仍要确认其中没有使用他人控制的音乐、画面、艺术品或表演。</p><h2>2. 阅读明确的许可</h2><p>开放许可会提前授予某些权利，但通常附带署名、禁止商业使用、禁止演绎或相同方式共享等条件。建议记录作者、来源 URL、许可名称和访问日期。</p><h2>3. 谨慎判断公共领域</h2><p>作品是否属于公共领域可能因国家不同。旧作品的新录音、修复、翻译、编曲或扫描也可能包含新的受保护元素。优先使用会清楚说明权利状态的可靠资料库。</p><h2>4. 向创作者或权利人取得许可</h2><p>没有明确许可时，应取得与实际用途一致的书面授权，包括作品、允许的行为、是否可商用、授权期限和署名要求。保存相关消息或协议。</p><h2>5. 区分保存与再次发布</h2><p>允许个人离线保存，不一定意味着可以重新上传、传播、编辑、出售或加入其他产品。每一种后续行为都需要单独判断。</p><h2>6. 尊重平台规则和访问控制</h2><p>不要绕过 DRM、付费墙、私密账户、登录验证、地域限制或其他技术保护。Pullvio 不会以规避这些限制为产品目标。</p><h2>保存前检查清单</h2><ol><li>能否识别创作者或权利人？</li><li>是否由您完整创作？</li><li>是否存在明确的公共领域声明或开放许可？</li><li>是否理解并满足许可的全部条件？</li><li>是否获得与用途相匹配的书面授权？</li><li>是否避开私密内容与访问控制？</li><li>是否记录来源、作者、许可和日期？</li></ol><p>不能确定时，不要把不确定当作许可。优先使用创作者提供的官方下载、请求确认、选择权利清楚的替代内容，或在后果重要时咨询专业人士。</p></>,
    },
  ],
  es: [
    {
      slug: "mp4-vs-mp3", eyebrow: "GUÍA DE FORMATOS", title: "MP4 o MP3: ¿qué formato deberías elegir?", readingTime: "6 min de lectura",
      description: "Compara MP4 y MP3 por uso, compatibilidad, calidad, edición y espacio para elegir el formato adecuado.",
      body: <><p>Elige MP4 cuando necesites imagen y sonido. Elige MP3 cuando solo quieras escuchar. Esta regla resuelve la mayoría de los casos, aunque la compatibilidad, el tamaño y la edición posterior también importan.</p><h2>MP4 conserva el video completo</h2><p>MP4 es un contenedor multimedia capaz de guardar video, audio, subtítulos y otros datos. Los teléfonos, ordenadores, navegadores, televisores y editores habituales suelen admitir combinaciones MP4 comunes.</p><p>Es la opción práctica para copias autorizadas donde la imagen tiene valor: videos propios, demostraciones permitidas, presentaciones o contenido visual para ver sin conexión.</p><h2>MP3 conserva únicamente el audio</h2><p>MP3 no incluye la imagen original. Al eliminar el video, el archivo suele ser mucho más pequeño y cómodo para reproductores, podcasts, clases de idiomas, entrevistas o notas de voz.</p><p>Convertir un archivo a MP3 no mejora el sonido original. Una fuente de baja calidad seguirá limitada por esa fuente, por lo que el bitrate máximo no siempre aporta una mejora audible.</p><h2>Calidad, tamaño y edición</h2><p>El tamaño depende de la duración, bitrate, códec, resolución y complejidad. Para voz, un bitrate moderado suele ser suficiente; la música puede justificar más información. Si vas a editar, conserva la fuente autorizada de mayor calidad y evita conversiones repetidas.</p><div className="content-callout"><strong>Elección rápida</strong><p>¿Necesitas la imagen? MP4. ¿Solo necesitas escuchar y ahorrar espacio? MP3. ¿Vas a editar o archivar? Conserva la mejor fuente que tengas derecho a utilizar.</p></div><h2>El formato no cambia los derechos</h2><p>Usa ambos formatos únicamente con obras propias, contenido de dominio público o licencia abierta dentro de sus condiciones, o material para el que tengas permiso u otro derecho legal.</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "GUÍA DE CALIDAD", title: "¿480p, 720p, 1080p, 2K o 4K?", readingTime: "7 min de lectura",
      description: "Comprende resolución, calidad de origen, tamaño de pantalla, ancho de banda y espacio antes de elegir.",
      body: <><p>1080p es una buena opción general para muchas pantallas modernas. Elige 720p cuando el espacio o la conexión sean limitados, y reserva 2K o 4K para fuentes que realmente contengan ese detalle y usos que puedan aprovecharlo.</p><h2>La resolución no es toda la calidad</h2><p>La resolución indica el número de píxeles, pero no describe el bitrate, la eficiencia del códec, los fotogramas por segundo, el color ni la grabación original. Un 1080p bien codificado puede verse mejor que un 4K excesivamente comprimido.</p><p>Ampliar una fuente 720p a un marco 4K crea más píxeles, pero no recupera detalle. Una herramienta fiable debe mostrar el límite real de la fuente.</p><h2>Qué resolución encaja con cada uso</h2><ul><li><strong>480p:</strong> archivos pequeños y conexiones lentas.</li><li><strong>720p:</strong> móviles, pantallas pequeñas y ahorro de espacio.</li><li><strong>1080p:</strong> portátiles, monitores, presentaciones y muchos televisores.</li><li><strong>1440p / 2K:</strong> monitores grandes y edición con recortes.</li><li><strong>2160p / 4K:</strong> pantallas grandes, archivo autorizado y edición exigente, con mayor coste de almacenamiento.</li></ul><h2>También importan los fotogramas y el bitrate</h2><p>El movimiento rápido necesita suficientes datos. Un video deportivo a 60 fps puede requerir más bitrate que una entrevista a 24 fps con la misma resolución. La compresión excesiva crea bloques y movimiento borroso.</p><div className="content-callout"><strong>Recomendación</strong><p>Empieza con 1080p cuando exista. Baja a 720p para archivos pequeños o conexiones limitadas. Sube a 2K o 4K solo cuando la fuente sea genuina y tengas un motivo claro.</p></div><h2>Sin promesas artificiales</h2><p>El flujo previsto de Pullvio mostrará únicamente las calidades disponibles en una fuente permitida. No prometeremos resoluciones para una plataforma hasta probar el proceso completo.</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "GUÍA DE USO RESPONSABLE", title: "Cómo guardar contenido online de forma responsable", readingTime: "8 min de lectura",
      description: "Revisa propiedad, dominio público, licencias abiertas, permiso del creador y reglas de la plataforma antes de guardar contenido.",
      body: <><p>El punto de partida más seguro es guardar contenido creado por ti, obras claramente de dominio público, material con licencia abierta usado dentro de sus condiciones o contenido cuyo titular te haya dado permiso. Poder acceder a una URL no concede automáticamente permiso para copiarla o reutilizarla.</p><div className="content-callout"><strong>Importante</strong><p>Esta guía ofrece información educativa general, no asesoramiento jurídico. Las excepciones de copyright, los contratos y las condiciones de las plataformas varían según el país y la situación.</p></div><h2>1. Empieza por la propiedad</h2><p>Conservar una copia de una obra que grabaste, produjiste y publicaste suele ser el caso más claro. Aun así, comprueba si contiene música, imágenes, arte o actuaciones controladas por otras personas.</p><h2>2. Lee la licencia completa</h2><p>Una licencia abierta puede exigir atribución, limitar el uso comercial, prohibir modificaciones o exigir compartir con la misma licencia. Guarda el autor, la URL, el nombre de la licencia y la fecha de acceso.</p><h2>3. Verifica el dominio público</h2><p>El estado de dominio público puede cambiar entre jurisdicciones. Una grabación, traducción, restauración o digitalización reciente de una obra antigua puede incluir elementos protegidos.</p><h2>4. Solicita permiso adecuado</h2><p>Cuando no exista una licencia clara, pide autorización por escrito que identifique la obra, los usos permitidos, la duración, el uso comercial y la atribución. Conserva el mensaje o acuerdo.</p><h2>5. Guardar no significa republicar</h2><p>El permiso para una copia personal no incluye necesariamente subir, distribuir, editar, vender o integrar la obra en otro producto. Evalúa cada acción por separado.</p><h2>6. Respeta las reglas y controles</h2><p>No eludas DRM, muros de pago, cuentas privadas, autenticación, restricciones geográficas ni otras protecciones técnicas. Pullvio no está pensado para ofrecer esos atajos.</p><h2>Lista de comprobación</h2><ol><li>¿Puedes identificar al creador o titular?</li><li>¿Creaste toda la obra?</li><li>¿Existe una declaración clara de dominio público o licencia?</li><li>¿Cumples todas sus condiciones?</li><li>¿Tienes permiso escrito para el uso previsto?</li><li>¿Evitas contenido privado y controles de acceso?</li><li>¿Has registrado fuente, autor, licencia y fecha?</li></ol><p>Si no estás seguro, no trates la duda como permiso. Usa la descarga oficial del creador, pide una aclaración, busca una alternativa con derechos claros o consulta a un profesional cuando las consecuencias sean importantes.</p></>,
    },
  ],
};

export function getLocalizedGuide(locale: LocalizedLocale, slug: string) {
  return localizedGuides[locale].find((guide) => guide.slug === slug);
}
