import type { Guide } from "@/lib/guides";
import type { LocalizedLocale } from "@/lib/i18n";
import type { PolicyPage } from "@/lib/policy-pages";

export const localizedAboutPages: Record<LocalizedLocale, PolicyPage> = {
  "zh-cn": {
    eyebrow: "关于 PULLVIO",
    title: "打造一种更清晰、更安心的媒体工作方式。",
    description: "Pullvio 是一款处于早期阶段的浏览器媒体工具，围绕清晰选择、负责任使用和诚实的产品沟通而设计。",
    body: <><h2>为什么要做 Pullvio</h2><p>许多在线媒体工具充斥着含糊的格式名称、干扰性广告、虚假按钮和无法验证的隐私承诺。Pullvio 希望提供一个更克制的选择：用清晰的界面说明工具能做什么、不能做什么，以及媒体处理过程中会发生什么。</p><p>目前上线的是前端内测版。它暂不处理媒体，也不出售订阅。我们先发布界面、无障碍体验、政策和教育内容，是为了在连接处理基础设施前发现并解决问题。</p><h2>我们正在建设什么</h2><p>第一个可用版本会刻意保持简单，先完成一个可靠的端到端流程，服务于用户自己拥有或有权保存的媒体。只有在来源、格式、账户功能和成本经过真实验证后，我们才会公布更多能力与付费额度。</p><h2>产品原则</h2><ul><li>不把模拟操作包装成已经可用的功能。</li><li>解释真实源画质，不承诺人为制造的高分辨率。</li><li>在主要工作流中清楚提示授权与负责任使用。</li><li>处理文件前先公开保留与删除规则。</li><li>让免费用户在手机和电脑上都能轻松理解和使用。</li></ul><div className="content-callout"><strong>独立内测产品</strong><p>Pullvio 与 YouTube、TikTok、Vimeo、X、SoundCloud 或其他媒体平台没有隶属或合作关系。只有当某个来源经过真实测试并可稳定使用后，我们才会发布对应说明。</p></div></>,
  },
  es: {
    eyebrow: "SOBRE PULLVIO",
    title: "Una forma más clara y tranquila de trabajar con contenido multimedia.",
    description: "Pullvio es una herramienta multimedia para el navegador en fase inicial, creada alrededor de decisiones claras, uso responsable y comunicación honesta.",
    body: <><h2>Por qué existe Pullvio</h2><p>Muchas herramientas multimedia online están rodeadas de formatos confusos, publicidad intrusiva, botones falsos y afirmaciones de privacidad difíciles de comprobar. Pullvio busca ser una alternativa más cuidada: un espacio enfocado que explica qué puede hacer, qué no puede hacer y qué ocurre durante el procesamiento.</p><p>La versión actual es una beta de interfaz. Todavía no procesa contenido ni vende suscripciones. Publicamos primero la experiencia, la accesibilidad, las políticas y las guías para poder revisarlas antes de conectar la infraestructura.</p><h2>Qué estamos construyendo</h2><p>La primera versión funcional será deliberadamente limitada. Se centrará en un flujo fiable para contenido que el usuario posee o tiene derecho a guardar. Añadiremos fuentes, formatos, cuentas y límites de pago solo después de comprobar que funcionan de forma estable y conocer sus costes reales.</p><h2>Nuestros principios</h2><ul><li>No presentar una simulación como una herramienta disponible.</li><li>Explicar la calidad de origen sin prometer resoluciones artificiales.</li><li>Hacer visibles los permisos y el uso responsable.</li><li>Publicar las reglas de conservación y eliminación antes de procesar archivos.</li><li>Mantener una experiencia gratuita clara en móvil y ordenador.</li></ul><div className="content-callout"><strong>Beta privada e independiente</strong><p>Pullvio no está afiliado con YouTube, TikTok, Vimeo, X, SoundCloud ni otras plataformas. Solo publicaremos una integración cuando la fuente haya sido probada y el flujo permitido funcione de manera fiable.</p></div></>,
  },
};

export const localizedGuideHubs: Record<LocalizedLocale, { eyebrow: string; title: string; description: string; guideLabel: string }> = {
  "zh-cn": { eyebrow: "PULLVIO 实用指南", title: "更明智地选择媒体格式。", description: "用清晰、实用的说明了解格式、分辨率、存储空间、源画质与负责任使用。", guideLabel: "指南" },
  es: { eyebrow: "GUÍAS DE PULLVIO", title: "Toma mejores decisiones multimedia.", description: "Explicaciones claras sobre formatos, resolución, almacenamiento, calidad de origen y uso responsable.", guideLabel: "GUÍA" },
};

export const localizedGuides: Record<LocalizedLocale, Guide[]> = {
  "zh-cn": [
    {
      slug: "mp4-vs-mp3", eyebrow: "格式指南", title: "MP4 和 MP3 有什么区别？应该选哪个？", readingTime: "阅读约 6 分钟",
      description: "从用途、兼容性、画质、编辑需求和存储空间比较 MP4 视频与 MP3 音频，选择适合自己的格式。",
      body: <><p>需要画面和声音时选择 MP4；只需要收听内容时选择 MP3。这个简单原则适用于大多数情况，但兼容性、文件大小和后续编辑也会影响最终选择。</p><h2>MP4 适合保留完整视频</h2><p>MP4 是一种多媒体容器，可以同时包含视频、音频、字幕和章节信息。手机、电脑、浏览器、电视、演示软件和常见剪辑工具通常都能打开标准 MP4 文件。</p><p>当画面本身有价值，例如自己的视频备份、获得授权的课程演示或需要离线观看的视觉内容时，MP4 是更实用的选择。</p><h2>MP3 适合只保留声音</h2><p>MP3 是音频格式，不包含原视频画面。去掉视频流后，文件通常更小，也更适合放入音乐播放器、播客应用、语言学习或笔记工作流。</p><p>把视频转换成 MP3 不会提升原始音质。低质量的源文件仍然受到源音频限制，因此没有必要盲目选择最高码率。</p><h2>画质、音质与文件大小</h2><p>文件大小取决于时长、码率、编码器、帧率、分辨率和内容复杂度。MP3 通常比 MP4 小很多；对于语音内容，中等码率往往已经足够，而音乐和复杂声音可能需要更高码率。</p><h2>如果还要编辑，尽量保留源文件</h2><p>反复转换会造成质量损失。如果计划剪辑、调色或长期归档，应保存最接近合法来源的高质量版本。MP3 适合收听，但通常不适合作为长期编辑母版。</p><div className="content-callout"><strong>快速选择</strong><p>需要画面就选 MP4；只需要声音和更小文件就选 MP3；需要长期编辑则保留您有权使用的最高质量源文件。</p></div><h2>格式不会改变版权归属</h2><p>选择 MP4 或 MP3 不会改变作品的权利状态。请只保存自己创作的内容、公共领域或符合开放许可条件的作品，以及您获得明确许可或拥有其他合法保存权利的媒体。</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "视频画质指南", title: "480p、720p、1080p、2K 与 4K 怎么选？", readingTime: "阅读约 7 分钟",
      description: "理解常见视频分辨率、真实源画质、屏幕尺寸、带宽和文件大小，选择适合的清晰度。",
      body: <><p>对于大多数现代屏幕，1080p 是兼顾清晰度和文件大小的默认选择。存储空间或网络有限时可选 720p；只有来源确实提供更多细节，并且设备或编辑流程能够利用时，2K 或 4K 才有明显价值。</p><h2>分辨率只是画质的一部分</h2><p>分辨率表示每一帧包含多少像素，但不能说明码率、编码效率、帧率、色彩和录制质量。编码良好的 1080p 可能比严重压缩的 4K 看起来更清晰。</p><p>把 720p 放大到 4K 只会增加像素数量，无法恢复原本不存在的细节。可信的工具应该展示来源真正提供的画质上限。</p><h2>常见分辨率适合什么场景</h2><ul><li><strong>480p：</strong>文件较小，适合慢速网络和画面不重要的内容。</li><li><strong>720p：</strong>适合手机、小屏幕和希望节省空间的用户。</li><li><strong>1080p：</strong>适合笔记本、显示器、演示和大多数电视，是通用首选。</li><li><strong>1440p / 2K：</strong>适合较大的高密度显示器、屏幕录制和需要裁切的编辑。</li><li><strong>2160p / 4K：</strong>适合大屏幕、近距离查看、授权归档和专业编辑，但文件与处理成本更高。</li></ul><h2>帧率和码率同样重要</h2><p>运动画面需要足够的帧率与码率。同为 1080p，60 帧运动视频通常比 24 帧访谈需要更多数据。压缩过度会产生马赛克、色带和运动模糊，无论分辨率标签多高都无法弥补。</p><div className="content-callout"><strong>推荐默认值</strong><p>来源存在 1080p 时先选 1080p；想减小文件或网络较慢时选 720p；只有真实来源和明确用途同时存在时才选择 2K 或 4K。</p></div><h2>不要制造虚假的画质承诺</h2><p>Pullvio 计划只展示合法来源实际提供的清晰度。媒体处理流程完成真实验证前，我们不会承诺任何平台一定支持某种分辨率。</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "负责任使用指南", title: "如何合法、负责任地保存在线媒体？", readingTime: "阅读约 8 分钟",
      description: "使用实用检查清单判断自己的作品、公共领域、开放许可、创作者授权和平台规则。",
      body: <><p>最安全的起点是：保存自己创作的媒体、明确进入公共领域的作品、按照许可条件使用的开放内容，或权利人明确允许您保存的内容。能够访问某个链接，并不自动代表拥有复制或再次使用的许可。</p><div className="content-callout"><strong>重要说明</strong><p>本指南只提供一般教育信息，不构成法律意见。版权例外、合同规则和平台条款会因国家与具体情况而不同。</p></div><h2>1. 先确认所有权</h2><p>如果作品由您录制、制作并上传，保留备份通常是最明确的场景。但仍要确认其中没有使用他人控制的音乐、画面、艺术品或表演。</p><h2>2. 阅读明确的许可</h2><p>开放许可会提前授予某些权利，但通常附带署名、禁止商业使用、禁止演绎或相同方式共享等条件。建议记录作者、来源 URL、许可名称和访问日期。</p><h2>3. 谨慎判断公共领域</h2><p>作品是否属于公共领域可能因国家不同。旧作品的新录音、修复、翻译、编曲或扫描也可能包含新的受保护元素。优先使用会清楚说明权利状态的可靠资料库。</p><h2>4. 向创作者或权利人取得许可</h2><p>没有明确许可时，应取得与实际用途一致的书面授权，包括作品、允许的行为、是否可商用、授权期限和署名要求。保存相关消息或协议。</p><h2>5. 区分保存与再次发布</h2><p>允许个人离线保存，不一定意味着可以重新上传、传播、编辑、出售或加入其他产品。每一种后续行为都需要单独判断。</p><h2>6. 尊重平台规则和访问控制</h2><p>不要绕过 DRM、付费墙、私密账户、登录验证、地域限制或其他技术保护。Pullvio 不会以规避这些限制为产品目标。</p><h2>保存前检查清单</h2><ol><li>能否识别创作者或权利人？</li><li>是否由您完整创作？</li><li>是否存在明确的公共领域声明或开放许可？</li><li>是否理解并满足许可的全部条件？</li><li>是否获得与用途相匹配的书面授权？</li><li>是否避开私密内容与访问控制？</li><li>是否记录来源、作者、许可和日期？</li></ol><p>不能确定时，不要把不确定当作许可。优先使用创作者提供的官方下载、请求确认、选择权利清楚的替代内容，或在后果重要时咨询专业人士。</p></>,
    },
  ],
  es: [
    {
      slug: "mp4-vs-mp3", eyebrow: "GUÍA DE FORMATOS", title: "MP4 o MP3: ¿qué formato deberías elegir?", readingTime: "6 min de lectura",
      description: "Compara MP4 y MP3 por uso, compatibilidad, calidad, edición y espacio para elegir el formato adecuado.",
      body: <><p>Elige MP4 cuando necesites imagen y sonido. Elige MP3 cuando solo quieras escuchar. Esta regla resuelve la mayoría de los casos, aunque la compatibilidad, el tamaño y la edición posterior también importan.</p><h2>MP4 conserva el video completo</h2><p>MP4 es un contenedor multimedia capaz de guardar video, audio, subtítulos y otros datos. Los teléfonos, ordenadores, navegadores, televisores y editores habituales suelen admitir combinaciones MP4 comunes.</p><p>Es la opción práctica para copias autorizadas donde la imagen tiene valor: videos propios, demostraciones permitidas, presentaciones o contenido visual para ver sin conexión.</p><h2>MP3 conserva únicamente el audio</h2><p>MP3 no incluye la imagen original. Al eliminar el video, el archivo suele ser mucho más pequeño y cómodo para reproductores, podcasts, clases de idiomas, entrevistas o notas de voz.</p><p>Convertir un archivo a MP3 no mejora el sonido original. Una fuente de baja calidad seguirá limitada por esa fuente, por lo que el bitrate máximo no siempre aporta una mejora audible.</p><h2>Calidad, tamaño y edición</h2><p>El tamaño depende de la duración, bitrate, códec, resolución y complejidad. Para voz, un bitrate moderado suele ser suficiente; la música puede justificar más información. Si vas a editar, conserva la fuente autorizada de mayor calidad y evita conversiones repetidas.</p><div className="content-callout"><strong>Elección rápida</strong><p>¿Necesitas la imagen? MP4. ¿Solo necesitas escuchar y ahorrar espacio? MP3. ¿Vas a editar o archivar? Conserva la mejor fuente que tengas derecho a utilizar.</p></div><h2>El formato no cambia los derechos</h2><p>Usa ambos formatos únicamente con obras propias, contenido de dominio público o licencia abierta dentro de sus condiciones, o material para el que tengas permiso u otro derecho legal.</p></>,
    },
    {
      slug: "video-resolution-guide", eyebrow: "GUÍA DE CALIDAD", title: "¿480p, 720p, 1080p, 2K o 4K?", readingTime: "7 min de lectura",
      description: "Comprende resolución, calidad de origen, tamaño de pantalla, ancho de banda y espacio antes de elegir.",
      body: <><p>1080p es una buena opción general para muchas pantallas modernas. Elige 720p cuando el espacio o la conexión sean limitados, y reserva 2K o 4K para fuentes que realmente contengan ese detalle y usos que puedan aprovecharlo.</p><h2>La resolución no es toda la calidad</h2><p>La resolución indica el número de píxeles, pero no describe el bitrate, la eficiencia del códec, los fotogramas por segundo, el color ni la grabación original. Un 1080p bien codificado puede verse mejor que un 4K excesivamente comprimido.</p><p>Ampliar una fuente 720p a un marco 4K crea más píxeles, pero no recupera detalle. Una herramienta fiable debe mostrar el límite real de la fuente.</p><h2>Qué resolución encaja con cada uso</h2><ul><li><strong>480p:</strong> archivos pequeños y conexiones lentas.</li><li><strong>720p:</strong> móviles, pantallas pequeñas y ahorro de espacio.</li><li><strong>1080p:</strong> portátiles, monitores, presentaciones y muchos televisores.</li><li><strong>1440p / 2K:</strong> monitores grandes y edición con recortes.</li><li><strong>2160p / 4K:</strong> pantallas grandes, archivo autorizado y edición exigente, con mayor coste de almacenamiento.</li></ul><h2>También importan los fotogramas y el bitrate</h2><p>El movimiento rápido necesita suficientes datos. Un video deportivo a 60 fps puede requerir más bitrate que una entrevista a 24 fps con la misma resolución. La compresión excesiva crea bloques y movimiento borroso.</p><div className="content-callout"><strong>Recomendación</strong><p>Empieza con 1080p cuando exista. Baja a 720p para archivos pequeños o conexiones limitadas. Sube a 2K o 4K solo cuando la fuente sea genuina y tengas un motivo claro.</p></div><h2>Sin promesas artificiales</h2><p>El flujo previsto de Pullvio mostrará únicamente las calidades disponibles en una fuente permitida. No prometeremos resoluciones para una plataforma hasta probar el proceso completo.</p></>,
    },
    {
      slug: "save-online-media-legally", eyebrow: "GUÍA DE USO RESPONSABLE", title: "Cómo guardar contenido online de forma responsable", readingTime: "8 min de lectura",
      description: "Revisa propiedad, dominio público, licencias abiertas, permiso del creador y reglas de la plataforma antes de guardar contenido.",
      body: <><p>El punto de partida más seguro es guardar contenido creado por ti, obras claramente de dominio público, material con licencia abierta usado dentro de sus condiciones o contenido cuyo titular te haya dado permiso. Poder acceder a una URL no concede automáticamente permiso para copiarla o reutilizarla.</p><div className="content-callout"><strong>Importante</strong><p>Esta guía ofrece información educativa general, no asesoramiento jurídico. Las excepciones de copyright, los contratos y las condiciones de las plataformas varían según el país y la situación.</p></div><h2>1. Empieza por la propiedad</h2><p>Conservar una copia de una obra que grabaste, produjiste y publicaste suele ser el caso más claro. Aun así, comprueba si contiene música, imágenes, arte o actuaciones controladas por otras personas.</p><h2>2. Lee la licencia completa</h2><p>Una licencia abierta puede exigir atribución, limitar el uso comercial, prohibir modificaciones o exigir compartir con la misma licencia. Guarda el autor, la URL, el nombre de la licencia y la fecha de acceso.</p><h2>3. Verifica el dominio público</h2><p>El estado de dominio público puede cambiar entre jurisdicciones. Una grabación, traducción, restauración o digitalización reciente de una obra antigua puede incluir elementos protegidos.</p><h2>4. Solicita permiso adecuado</h2><p>Cuando no exista una licencia clara, pide autorización por escrito que identifique la obra, los usos permitidos, la duración, el uso comercial y la atribución. Conserva el mensaje o acuerdo.</p><h2>5. Guardar no significa republicar</h2><p>El permiso para una copia personal no incluye necesariamente subir, distribuir, editar, vender o integrar la obra en otro producto. Evalúa cada acción por separado.</p><h2>6. Respeta las reglas y controles</h2><p>No eludas DRM, muros de pago, cuentas privadas, autenticación, restricciones geográficas ni otras protecciones técnicas. Pullvio no está pensado para ofrecer esos atajos.</p><h2>Lista de comprobación</h2><ol><li>¿Puedes identificar al creador o titular?</li><li>¿Creaste toda la obra?</li><li>¿Existe una declaración clara de dominio público o licencia?</li><li>¿Cumples todas sus condiciones?</li><li>¿Tienes permiso escrito para el uso previsto?</li><li>¿Evitas contenido privado y controles de acceso?</li><li>¿Has registrado fuente, autor, licencia y fecha?</li></ol><p>Si no estás seguro, no trates la duda como permiso. Usa la descarga oficial del creador, pide una aclaración, busca una alternativa con derechos claros o consulta a un profesional cuando las consecuencias sean importantes.</p></>,
    },
  ],
};

export function getLocalizedGuide(locale: LocalizedLocale, slug: string) {
  return localizedGuides[locale].find((guide) => guide.slug === slug);
}
