import type { ReactNode } from "react";

export type PolicyPage = { title: string; description: string; eyebrow: string; body: ReactNode };

export const policyPages: Record<string, PolicyPage> = {
  about: {
    eyebrow: "ABOUT PULLVIO", title: "Building a calmer way to work with media.", description: "Pullvio is an early-stage, browser-based media product being developed around clear choices, responsible use, and honest product communication.",
    body: <><h2>Why Pullvio exists</h2><p>Online media workflows are often surrounded by confusing format labels, intrusive advertising, fake buttons, and unclear privacy claims. Pullvio is an attempt to design a more considered alternative: a focused workspace that explains what it can do, what it cannot do, and what happens to a file during processing.</p><p>The current release is a frontend private beta. It does not process media or sell a subscription. We published this foundation first so the interface, accessibility, policies, and educational content can be reviewed before infrastructure is connected.</p><h2>What we are building toward</h2><p>The first functional release will be deliberately limited. It will focus on one reliable end-to-end workflow for media a user owns or has the right to save. Additional sources, formats, account features, and paid limits will be published only after they work reliably and their operational costs are understood.</p><h2>Our product principles</h2><ul><li>Do not present a simulated action as a working tool.</li><li>Explain source quality instead of promising artificial resolution.</li><li>Make permission and responsible use visible in the main workflow.</li><li>Document retention and deletion behavior before processing files.</li><li>Keep the free entry experience understandable on mobile and desktop.</li></ul><div className="content-callout"><strong>Independent private beta</strong><p>Pullvio is not affiliated with YouTube, TikTok, Vimeo, X, SoundCloud, or any other media platform. Platform names will appear only when a tested integration is genuinely available.</p></div></>,
  },
  contact: {
    eyebrow: "CONTACT", title: "Talk to the Pullvio team.", description: "Questions about the beta, privacy, accessibility, or copyright can be directed to the appropriate Pullvio inbox.",
    body: <><h2>General and beta feedback</h2><p>Email <a href="mailto:hello@pullvio.com">hello@pullvio.com</a> for product feedback, accessibility issues, partnership questions, or corrections to our published guides.</p><h2>Privacy questions</h2><p>Email <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a> for questions about personal data, cookies, account information, or a privacy request.</p><h2>Copyright notices</h2><p>Email <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a> for copyright and takedown matters. Include enough information to identify the work, the relevant location, your authority to act, and a reliable way to contact you.</p><h2>Response expectations</h2><p>Pullvio is currently an early-stage private beta. We aim to acknowledge legitimate support and policy messages within five business days, but this is not an emergency or real-time support channel.</p><div className="content-callout"><strong>Before public launch</strong><p>These domain inboxes must be active and monitored before this page is published on the production domain.</p></div></>,
  },
  privacy: {
    eyebrow: "PRIVACY", title: "Privacy policy.", description: "This policy explains the limited data used by the Pullvio frontend beta and how the policy will change before media processing becomes available.",
    body: <><h2>Current beta scope</h2><p>The current public release is a frontend and content beta. It does not upload, analyze, convert, or retain media files. It also does not currently sell a paid plan.</p><h2>Data the site may handle</h2><ul><li><strong>Basic access data:</strong> hosting and security providers may process IP address, browser type, requested URL, timestamps, and diagnostic information needed to deliver and protect the site.</li><li><strong>Local preferences:</strong> theme and language preferences may be stored in your browser using local storage.</li><li><strong>Account data:</strong> if authentication is enabled, the authentication provider may process your email address, account identifier, session tokens, and login method.</li><li><strong>Messages you send:</strong> if you contact Pullvio, we receive the address and content you choose to provide.</li></ul><h2>Cookies and local storage</h2><p>Authentication, when enabled, uses security cookies to maintain a signed-in session. Theme and language choices are stored locally in the browser. We will publish a separate consent mechanism before introducing non-essential advertising or marketing cookies.</p><h2>Service providers</h2><p>The site may rely on hosting, authentication, email, security, and analytics providers. Production providers and international transfer details will be documented here before the corresponding feature is enabled.</p><h2>Retention and requests</h2><p>Access logs are retained according to hosting and security needs. Support messages are retained while needed to respond and maintain records. You may request access, correction, or deletion by emailing <a href="mailto:privacy@pullvio.com">privacy@pullvio.com</a>, subject to applicable law and necessary security records.</p><h2>Future media processing</h2><p>Before media processing goes live, this policy will specify temporary file locations, deletion schedules, job logs, download history behavior, subprocessors, and choices available to Free and Pro users. We will not rely on this beta policy to describe a materially different production service.</p></>,
  },
  terms: {
    eyebrow: "TERMS", title: "Terms of use.", description: "These beta terms govern access to the Pullvio website, published guides, account preview, and future product information.",
    body: <><h2>Beta status</h2><p>Pullvio is currently provided as an informational frontend beta. Media processing and paid subscriptions are not available in this release. Features, dates, limits, and pricing shown in roadmap material are not binding commitments.</p><h2>Permitted use</h2><p>You may use the site for lawful evaluation, reading, and account testing. When media features become available, you must use them only for content you own, content in the public domain, openly licensed content used within its license, or content you otherwise have permission or a legal right to save.</p><h2>Prohibited behavior</h2><ul><li>Attempting to bypass access controls, DRM, subscriptions, private accounts, or technical restrictions.</li><li>Using the service to infringe copyright, privacy, publicity, contractual, or other rights.</li><li>Automated abuse, excessive requests, security testing without permission, malware, or interference with the service.</li><li>Misrepresenting Pullvio as affiliated with a third-party platform.</li></ul><h2>No legal advice or guaranteed availability</h2><p>Published guides provide general educational information and are not legal advice. Laws and platform terms vary. Beta content is provided as available and may change, move, or be withdrawn.</p><h2>Accounts and future paid plans</h2><p>You are responsible for maintaining account security. Additional subscription, billing, cancellation, and refund terms will be presented before any paid plan can be purchased.</p><h2>Contact</h2><p>Questions about these terms may be sent to <a href="mailto:hello@pullvio.com">hello@pullvio.com</a>.</p></>,
  },
  copyright: {
    eyebrow: "COPYRIGHT", title: "Copyright and takedown policy.", description: "Pullvio is intended for authorized media workflows and provides a channel for rights holders to report specific concerns.",
    body: <><h2>Respect for creative work</h2><p>Pullvio is designed for a user’s own uploads, public-domain material, openly licensed works, and content the user has permission or another valid legal basis to save. The service is not intended to bypass DRM, paid access, private accounts, or platform restrictions.</p><h2>Submitting a notice</h2><p>Send copyright notices to <a href="mailto:copyright@pullvio.com">copyright@pullvio.com</a>. A useful notice should include:</p><ol><li>Identification of the copyrighted work or authorized representative.</li><li>The exact Pullvio URL, job reference, or other information needed to locate the reported material or activity.</li><li>Your name, organization if applicable, and reliable contact details.</li><li>A statement explaining why you believe the use is unauthorized.</li><li>A statement that the information is accurate and that you are authorized to act.</li><li>Your physical or electronic signature where required.</li></ol><h2>Review and response</h2><p>We may request clarification, restrict access, preserve necessary records, or take other proportionate steps while reviewing a complete notice. Knowingly false or materially misleading notices may create liability.</p><h2>Counter-notices and repeat misuse</h2><p>Where applicable, users may be offered a process to respond to a notice. Repeated infringement or abuse may result in account restrictions or termination when account and processing features are live.</p><div className="content-callout"><strong>Current beta limitation</strong><p>The frontend beta does not host or process user media. This policy establishes the reporting channel that will be used before those capabilities launch.</p></div></>,
  },
  "acceptable-use": {
    eyebrow: "ACCEPTABLE USE", title: "Acceptable use policy.", description: "The Pullvio product is being designed for legitimate personal, creative, archival, and educational workflows—not access-control circumvention.",
    body: <><h2>Acceptable examples</h2><ul><li>Backing up media you created and uploaded yourself.</li><li>Saving public-domain material or openly licensed work in accordance with its license.</li><li>Working with media for which the creator or rights holder gave you permission.</li><li>Preparing authorized references for editing, teaching, research, accessibility, or offline use.</li></ul><h2>Uses that are not accepted</h2><ul><li>Downloading or distributing copyrighted material without permission or another valid legal basis.</li><li>Bypassing DRM, paywalls, authentication, private-account controls, geographic restrictions, or other access controls.</li><li>Processing illegal, exploitative, abusive, or privacy-invasive content.</li><li>Using automation to overwhelm the service, evade limits, scrape results, or resell access without authorization.</li><li>Introducing malware, probing infrastructure, or interfering with other users.</li></ul><h2>Enforcement</h2><p>When processing and accounts launch, Pullvio may limit requests, suspend jobs, restrict accounts, preserve security records, or cooperate with valid legal processes. Enforcement decisions may consider intent, severity, recurrence, and risk to other people or the service.</p><h2>Your responsibility</h2><p>You are responsible for understanding the rights attached to the media you use and for complying with applicable law and platform terms. A technically accessible URL does not by itself establish permission to save or reuse its content.</p></>,
  },
};
