alter table public.download_artifacts
  add column if not exists id bigint generated by default as identity,
  add column if not exists artifact_kind text,
  add column if not exists file_size_bytes bigint;

update public.download_artifacts as artifacts
set artifact_kind = case
      when artifacts.content_type like 'video/%' then 'video'
      when artifacts.content_type like 'audio/%' then 'audio'
      when artifacts.content_type like 'image/%' then 'thumbnail'
      else jobs.media_kind
    end,
    file_size_bytes = coalesce(artifacts.file_size_bytes, jobs.file_size_bytes, 0)
from public.download_jobs as jobs
where jobs.id = artifacts.job_id
  and (artifacts.artifact_kind is null or artifacts.file_size_bytes is null);

update public.download_artifacts
set expires_at = now() + interval '24 hours'
where expires_at is null;

alter table public.download_artifacts
  alter column artifact_kind set not null,
  alter column file_size_bytes set not null,
  alter column expires_at set not null,
  drop constraint if exists download_artifacts_pkey;

alter table public.download_artifacts
  add constraint download_artifacts_pkey primary key (id),
  add constraint download_artifacts_job_kind_unique unique (job_id, artifact_kind),
  add constraint download_artifacts_kind_check check (
    artifact_kind in ('video', 'audio', 'thumbnail')
  ),
  add constraint download_artifacts_file_size_check check (
    file_size_bytes >= 0 and file_size_bytes <= 2147483648
  );

create index if not exists download_artifacts_job_id_idx
  on public.download_artifacts (job_id);

create or replace function public.complete_media_job_v2(
  p_job_id uuid,
  p_worker_id text,
  p_artifacts jsonb,
  p_title text,
  p_thumbnail_url text,
  p_duration_seconds integer,
  p_processing_seconds bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job public.download_jobs%rowtype;
  v_artifact jsonb;
  v_expires_at timestamptz := now() + interval '24 hours';
  v_kind text;
  v_bucket text;
  v_path text;
  v_content_type text;
  v_disposition text;
  v_checksum text;
  v_size bigint;
  v_primary_size bigint := 0;
  v_total_size bigint := 0;
  v_count integer;
begin
  select * into v_job
  from public.download_jobs
  where id = p_job_id and status = 'processing' and worker_id = p_worker_id
  for update;
  if not found or v_job.cancellation_requested_at is not null then return false; end if;

  if jsonb_typeof(p_artifacts) <> 'array' then
    raise exception 'Artifacts must be a JSON array' using errcode = '22023';
  end if;
  v_count := jsonb_array_length(p_artifacts);
  if v_count < 1 or v_count > 3 then
    raise exception 'Artifact count is invalid' using errcode = '22023';
  end if;
  if (select count(distinct value->>'kind') from jsonb_array_elements(p_artifacts)) <> v_count then
    raise exception 'Artifact kinds must be unique' using errcode = '22023';
  end if;

  delete from public.download_artifacts where job_id = p_job_id;

  for v_artifact in select value from jsonb_array_elements(p_artifacts)
  loop
    v_kind := v_artifact->>'kind';
    v_bucket := v_artifact->>'storageBucket';
    v_path := v_artifact->>'storagePath';
    v_content_type := v_artifact->>'contentType';
    v_disposition := v_artifact->>'contentDisposition';
    v_checksum := v_artifact->>'checksumSha256';
    v_size := (v_artifact->>'fileSizeBytes')::bigint;

    if v_kind not in ('video', 'audio', 'thumbnail')
      or v_bucket <> 'pullvio'
      or v_path !~ ('^outputs/' || p_job_id::text || '/[0-9a-f]{32}[.](mp4|mp3|jpg)$')
      or v_checksum !~ '^[0-9a-f]{64}$'
      or v_size <= 0 or v_size > 2147483648
      or (v_kind = 'video' and v_content_type <> 'video/mp4')
      or (v_kind = 'audio' and v_content_type <> 'audio/mpeg')
      or (v_kind = 'thumbnail' and v_content_type <> 'image/jpeg')
      or v_disposition !~ ('^attachment; filename="pullvio-' || p_job_id::text || '-(video[.]mp4|audio[.]mp3|cover[.]jpg)"$')
    then
      raise exception 'Artifact metadata is invalid' using errcode = '22023';
    end if;

    insert into public.download_artifacts (
      job_id, artifact_kind, storage_bucket, storage_path, content_type,
      content_disposition, checksum_sha256, file_size_bytes, expires_at
    ) values (
      p_job_id, v_kind, v_bucket, v_path, v_content_type,
      v_disposition, v_checksum, v_size, v_expires_at
    );
    v_total_size := v_total_size + v_size;
    if v_kind = v_job.media_kind then v_primary_size := v_size; end if;
  end loop;

  if v_primary_size <= 0 then
    raise exception 'The requested primary artifact is missing' using errcode = '22023';
  end if;

  update public.download_jobs
  set status = 'ready',
      title = left(nullif(btrim(p_title), ''), 500),
      thumbnail_url = case when p_thumbnail_url ~* '^https?://' then left(p_thumbnail_url, 2048) else null end,
      original_duration_seconds = p_duration_seconds,
      file_size_bytes = v_primary_size,
      failure_code = null,
      completed_at = now(),
      lease_expires_at = null,
      worker_id = null
  where id = p_job_id;

  if v_job.user_id is not null then
    insert into public.usage_daily (
      user_id, usage_date, plan_code, quota_limit, jobs_succeeded,
      bytes_output, processing_seconds
    ) values (
      v_job.user_id, current_date, 'free', null, 1,
      v_total_size, greatest(p_processing_seconds, 0)
    ) on conflict (user_id, usage_date) do update
      set jobs_succeeded = public.usage_daily.jobs_succeeded + 1,
          bytes_output = public.usage_daily.bytes_output + v_total_size,
          processing_seconds = public.usage_daily.processing_seconds + greatest(p_processing_seconds, 0),
          updated_at = now();
  end if;

  return true;
end;
$$;

revoke all on function public.complete_media_job_v2(
  uuid, text, jsonb, text, text, integer, bigint
) from public, anon, authenticated;
grant execute on function public.complete_media_job_v2(
  uuid, text, jsonb, text, text, integer, bigint
) to service_role;

-- Keep the currently deployed single-artifact worker safe during the rolling
-- migration. Its expiry argument is intentionally ignored so all newly committed
-- artifacts receive the database-controlled 24-hour window.
create or replace function public.complete_media_job(
  p_job_id uuid,
  p_worker_id text,
  p_storage_bucket text,
  p_storage_path text,
  p_content_type text,
  p_content_disposition text,
  p_checksum_sha256 text,
  p_title text,
  p_thumbnail_url text,
  p_duration_seconds integer,
  p_file_size_bytes bigint,
  p_processing_seconds bigint,
  p_artifact_expires_at timestamptz
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_kind text;
begin
  select media_kind into v_kind
  from public.download_jobs
  where id = p_job_id;
  if v_kind is null then return false; end if;

  return public.complete_media_job_v2(
    p_job_id,
    p_worker_id,
    jsonb_build_array(jsonb_build_object(
      'kind', v_kind,
      'storageBucket', p_storage_bucket,
      'storagePath', p_storage_path,
      'contentType', p_content_type,
      'contentDisposition', case
        when v_kind = 'video' then 'attachment; filename="pullvio-' || p_job_id::text || '-video.mp4"'
        else 'attachment; filename="pullvio-' || p_job_id::text || '-audio.mp3"'
      end,
      'checksumSha256', p_checksum_sha256,
      'fileSizeBytes', p_file_size_bytes
    )),
    p_title,
    p_thumbnail_url,
    p_duration_seconds,
    p_processing_seconds
  );
end;
$$;

comment on column public.download_artifacts.artifact_kind is
  'Download role within a media job: requested video/audio or optional thumbnail.';
comment on column public.download_artifacts.expires_at is
  'Hard application access expiry; currently assigned 24 hours after job completion.';
